### ISSUE TITLE
Integrate updater and migrate to 1.0 API

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/tauri-action#108]
The GitHub actions should provide everything required for the updater and should expose the built artifacts as well.

- [x] Updater artifacts
- [x] Migrate to 1.0 
- [ ] Code signing

Github Actions should be fully compatible with the current Tauri version.

**Comment by lemarier** [comment]
@jbolda can you assign me please so I can follow on this? Thanks!

**Comment by lucasfernog** [comment]
Updated to 1.0 beta-rc on #98

**Comment by FabianLars** [comment]
I don't think there is much else we can do here. A possible additional feature to auto generate a updater json file is tracked in #251.
