### ISSUE TITLE
ubuntu setup

### ISSUE THREAD

**Issue by lukeed** [tauri-apps/tauri-action#147]
Following the README instructions failed to build a basic Tauri application on `ubuntu-latest`

It results in this error:

```
  --- stderr
  `"pkg-config" "--libs" "--cflags" "gtksourceview-3.0" "gtksourceview-3.0 >= 3.0"` did not exit successfully: exit status: 1
  --- stderr
  Package gtksourceview-3.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gtksourceview-3.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gtksourceview-3.0' found
  Package gtksourceview-3.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gtksourceview-3.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gtksourceview-3.0' found
```

The following command is the only thing that worked (found via Discord search):

```sh
 sudo apt-get install -y libgtk-3-dev libgtksourceview-3.0-dev webkit2gtk-4.0 libappindicator3-dev
```

I also tried this, which failed with the same error:

```sh
sudo apt-get install -y libwebkit2gtk-4.0-dev
```

**Comment by lucasfernog** [comment]
We need to change the readme example.

**Comment by lukeed** [comment]
Correct :) There's probably a narrower/more concise list of packages to install. TBH, I barely know what I'm doing, so I'll leave that up to someone else :D

**Comment by RyKilleen** [comment]
@lucasfernog @lukeed any chance there's an ideal default to point to, living out in the wild?

I'm running into this issue, [as well as another](https://github.com/RyKilleen/brancato/runs/5469347018?check_suite_focus=true#step:7:527):
```
thread 'main' panicked at 'error found during tauri-build: unknown field `tsp`, expected one of `digestAlgorithm`, `certificateThumbprint`, `timestampUrl`, `webviewFixedRuntimePath`, `wix` at line 1 column 1217', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-build-1.0.0-rc.3\src\lib.rs:146:5
```
and figured there might be a better default example out there.

**Comment by lucasfernog** [comment]
@RyKilleen you need to update the @tauri-apps/cli package to `1.0.0-rc.7`
