### ISSUE TITLE
Creates `release` even if failed pipeline

### ISSUE THREAD

**Issue by lukeed** [tauri-apps/tauri-action#149]
If/When one of the platform matrix targets fail, all others continue to upload their asset(s) to the release.

Expected the failed pipeline to _not_ create a release until all `matrix` targets were successful.

**Comment by lucasfernog** [comment]
We'll double check this but I don't think this is possible. Since each matrix job is ran separately, it's a little tricky to do it, probably needs another job that runs on finish. You can mark the release as a draft release though.

**Comment by lukeed** [comment]
It's possible – I only have partially-failed `Release` pipelines (darn Windows), yet I have a GH release for each attempt.

---

Edit: Sorry, I misunderstood you. I thought you were saying that it was impossible for this problem to exist 🙈 

I think this can be done via [`job.needs`](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#needs-context). It might take a bit of plumbing, but each matrix pipeline could have a final step (eg, `upload`) that `needs` all others' `build`-step to succeed.

**Comment by lukeed** [comment]
> You can mark the release as a draft release though.

See #6  – I have `draft: true` set and it's ignored

**Comment by FabianLars** [comment]
Yeah, i don't think this is possible to solve inside tauri-action in a sane way, but we now have a readme example which uses a different action to make the draft release public after all assets were uploaded. https://github.com/tauri-apps/tauri-action#uploading-the-artifacts-to-a-release
