### ISSUE TITLE
Optimize release binary (anti-bloat)

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/tauri-action#150]
Optimize release binary with @chippers suggestions

One of them is:
```
cargo +nightly build --release -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
```

https://tauri.studio/en/docs/usage/guides/bundler/anti-bloat/

**Comment by lucasfernog** [comment]
We can also automatically run `strip` behind some configuration.

**Comment by chippers** [comment]
cargo is supposed to have a nightly feature `-Z strip=symbols` which strips during the linking phase, but on the last nightly version I didn't get it to work.  It might work now

edit: also that command needs to specify the target triple to work (like `--target x86_64-unknown-linux-gnu`) and the result will be in `target/x86_64-unknown-linux-gnu/release`

**Comment by chippers** [comment]
@lucasfernog @lemarier did we ever resolve this? the `strip` option is now stable on `rustc` but not on `cargo`

**Comment by lucasfernog** [comment]
We run `strip` by default on unix now (on the CLI).

**Comment by chippers** [comment]
> We run `strip` by default on unix now (on the CLI).

im like 99% sure that the current cargo release doesn't recognize the strip option

**Comment by FabianLars** [comment]
What Lucas meant is that our cli executes the OS' strip command

**Comment by FabianLars** [comment]
With https://github.com/tauri-apps/tauri/pull/3863 we now expect the user to use rust's built-in `strip` config (stabilized in 1.59), see [here](https://doc.rust-lang.org/cargo/reference/profiles.html#strip) for the official docs.

And imo nightly-only things like `build-std` shouldn't be part of the action (users should be able to do this themselves using existing configs)
