### ISSUE TITLE
Central version bump.

### ISSUE THREAD

**Issue by Blakeinstein** [tauri-apps/tauri-action#151]
**Is your feature request related to a problem? Please describe.**
Any time a version bump is required. I need to update three locations
1. `tauri.conf.json` : Build version on the binaries.
2. `package.json`: Version number for github releases
3. `cargo.toml`: I dont think this is honored anywhere, except when using cargo run.

**Describe the solution you'd like**
A central source of truth? Can tauri.conf.json not be a part of package.json?

**Additional context**
My folder setup is unique since, my project was originally a rust project using webview. So at build time I need to restructure my folder like [this](
https://github.com/Blakeinstein/Bloop/blob/7191e01039e70f86c8119618917b5341a0dc6e30/.github/workflows/main.yml#L51-L58), so that I can create installers via the build cli.

**Comment by kasper9n** [comment]
`package.json` isn't necessary for tauri, so you don't need to specify a version there (*except currently the tauri action uses package.json to get the version).

The version in `tauri.conf.json` is optional. By default, it uses the version from `Cargo.toml`.

The version in `Cargo.toml` is required by Cargo no matter what, so imo it makes sense to go for that.

**Comment by Blakeinstein** [comment]
While yes. package.json reflects the version shown in the github release.

tauri.conf.json is most likely the version provides by the package meta inside a tauri app provided by the api.

**Comment by kasper9n** [comment]
If you specify a version in `tauri.conf.json`, yes, but otherwise it defaults to `Cargo.toml`

**Comment by jkeen** [comment]
I'm new to Tauri and this little speed bump hit me today. Did y'all figure out a shortcut in the last three years?

**Comment by davidenke** [comment]
> I'm new to Tauri and this little speed bump hit me today. Did y'all figure out a shortcut in the last three years?

Maybe a bit late, but another 4 months later it hit me as well...

In a GitHub action I first determine the next version using [`get-next-version`](https://github.com/thenativeweb/get-next-version) and then bump all three versions manually:

```bash
# package.json
echo "$(jq '.version="${{ env.NEXT_VERSION }}"' package.json)" > package.json
# tauri.conf.json
echo "$(jq '.version="${{ env.NEXT_VERSION }}"' src-tauri/tauri.conf.json)" > src-tauri/tauri.conf.json
# cargo.toml
cd src-tauri && cargo install cargo-bump && cargo bump ${{ env.NEXT_VERSION }}
```

If used with an actual environment variable, this would look like this:
```bash
# package.json
echo "$(jq --arg next_version "${NEXT_VERSION}" '.version=$next_version' package.json)" > package.json
# tauri.conf.json
echo "$(jq --arg next_version "${NEXT_VERSION}" '.version=$next_version' src-tauri/tauri.conf.json)" > src-tauri/tauri.conf.json
# cargo.toml
cd src-tauri && cargo install cargo-bump && cargo bump ${NEXT_VERSION}
```
