### ISSUE TITLE
[Question] is this dependent on language and framework of the web app?

### ISSUE THREAD

**Issue by simkimsia** [tauri-apps/tauri-action#207]

**Comment by FabianLars** [comment]
No, just like tauri doesn't care about your frontend choices, this action doesn't either.
You build/compile your webapp separately, either like in the readme example in an extra workflow step (`yarn && yarn build` in this case) or via `beforeBuildCommand` in `tauri.conf.json` (you probably still need to use an extra workflow step to install the dependencies first)
