### ISSUE TITLE
Can't find Windows artifact

### ISSUE THREAD

**Issue by dserv-nh** [tauri-apps/tauri-action#225]
After updating to tauri 1.0.0-rc1:

```
info: running light to produce D:\a\project\project\src-tauri\target\release\bundle/msi/Project_0.6.0_x64_en-US.msi
    Finished 1 bundle at:
        D:\a\project\project\src-tauri\target\release\bundle/msi/Project_0.6.0_x64_en-US.msi
Done in 674.97s.
Error: No artifacts were found.
```

https://github.com/tauri-apps/tauri-action/blob/dev/packages/core/index.ts#L312-L325
I noticed that it would search here for `Project_0.6.0_x64.msi` but the file is now named Project_0.6.0_x64_**en-US**.msi
It's only the case for the Windows build

**Comment by FabianLars** [comment]
Yeah that's a known issue and indeed needs some changes to fix it. Thanks for opening a tracking issue ❤️

**Comment by jdukewich** [comment]
Opened a PR (#227) to try to address this. @dserv-nh you can use the action from my fork for now if it is urgently needed.

**Comment by dserv-nh** [comment]
@jdukewich Despite the review in the PR, it works like a charm for my use case. Thanks!
