### ISSUE TITLE
No Css in Windows-build

### ISSUE THREAD

**Issue by Septias** [tauri-apps/tauri-action#241]
Hi,

the build of my tauri-action does not ship with css.

Project: https://github.com/Septias/reddit_wallpapers
Releas: https://github.com/Septias/reddit_wallpapers/releases/tag/app-v0.1.0

I created the project with the default template for vite and switched the vue-part to [vitesse](https://github.com/antfu/vitesse). 
The preview (pnpm preview) looks fine so I guess the css gets bundled correctly.

best regards,
Septias

**Comment by FabianLars** [comment]
A couple notes about your main.yml
1) Remove the "install tauri bundler" step.
2) remove the "&& yarn build" step since you do that in your `beforeBuildCommand`, speaking of which you may want to use pnpm in your build script too since you do it everywhere else.

Also this was pretty hard to test/set up :/ (actually i still wasn't able to set it up in a way that it can actually fetch something but at least the app doesn't crash).
On a side note, building it locally indeed works fine.

**Comment by Septias** [comment]
Ah sorry, yes of cause it's kind of a pain to set it up. I provided some mock-data, which you can import instead of using tauriapi to fetch everything etc.
I created a branch `testing` which utilizes that and with which one is able to see how it should look. Just pull that one and use `pnpm dev` (or npm run dev) to run the local dev-server.

**Comment by Septias** [comment]
Referencing your first hint 
> `Remove the "install tauri bundler" step.` 

I didn't know there is an updated version of that script. The [marketplace](https://github.com/marketplace/actions/tauri-action) still uses an older version I guess.

**Comment by FabianLars** [comment]
The marketplace action is not ours.

**Comment by Septias** [comment]
ahhhh, that explains something I guess :joy: 
I just copied the script from this repo and started it. let's see if it works.

**Comment by Septias** [comment]
Sadly the other script doesn't work too. What bugs me is that everything else is working, like html and js are fine. Only css not working?

**Comment by FabianLars** [comment]
Can you add the `devtools` feature flag to your tauri dependency in cargo.toml and run the workflow again?

Super weird that it's fine if built locally but broken on GH action...

**Comment by Septias** [comment]
I've enabled the devtools, what now?

**Comment by FabianLars** [comment]
Build (and upload) the app via gh actions and check the console for errors (or the sources&networks tabs)

**Comment by Septias** [comment]
Ok, weirdly they seem to be included and referenced, but have no effect? How can that happen?
![image](https://user-images.githubusercontent.com/39526136/158405475-935ff1fd-6a44-42bd-98ba-171e2f69d18f.png)

**Comment by Septias** [comment]
Okay it seems like an export-error 🤔
I just looked at some referenced classes in the html, and they are not present in the css-file.
Might have to contact uno-css dev then.

**Comment by FabianLars** [comment]
Still weird that it seemingly happens only in a workflow and not if built locally 🤔 Anyway, good luck!
