### ISSUE TITLE
OSX and Windows do not build with action used as in README

### ISSUE THREAD

**Issue by ianmcorvidae** [tauri-apps/tauri-action#25]
Ubuntu does fine, but for OSX, end of the log (replacing the name of my project with `<name>`) :

```
Disk image done
    Finished 2 bundles at:
        /Users/runner/work/<name>/<name>/src-tauri/target/release/bundle/osx/<name>_0.1.0_x64.app
        /Users/runner/work/<name>/<name>/src-tauri/target/release/bundle/dmg/<name>_0.1.0_x64.dmg

 app:tauri Shutting down tauri process... +1ms
##[error]No artifacts were found.
```

and for windows:

```
info: running light to produce D:\a\<name>\<name>\src-tauri\target\release\bundle/msi/<name>_0.1.0_x64.msi
Windows Installer XML Toolset Linker version 3.11.2.4516
Copyright (c) .NET Foundation and contributors. All rights reserved.

    Finished 1 bundle at:
        D:\a\<name>\<name>\src-tauri\target\release\bundle/msi/<name>_0.1.0_x64.msi

 app:tauri Shutting down tauri process... +1ms
##[error]No artifacts were found.
```

This is using the action like below:

```yaml
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "App v__VERSION__"
        body: "See the assets to download this version and install."
        draft: true
        prerelease: false
```

(direct copy-paste from README -- I've since fixed the `body` and `draft` keys)

What needs to be done to have this work? Clearly the action is creating the artifacts fine, just not retaining them.

**Comment by lucasfernog** [comment]
This is because I didn`t update the action yet, sorry about that. Gonna do it right now.

**Comment by ianmcorvidae** [comment]
I appreciate the fast response! I'll keep an eye here and update my action if needed/retry this once it's all finished.

**Comment by lucasfernog** [comment]
Version 0.0.7 published :) let me know how it goes.

**Comment by ianmcorvidae** [comment]
Looks like it's working -- at least, it built something! I'll test it eventually, but at this point if it's broken it's probably my fault and not the github action. Thanks again!

**Comment by lucasfernog** [comment]
Well it could be the action's fault so let me know if something is wrong.
