### ISSUE TITLE
ability to specify a target

### ISSUE THREAD

**Issue by Niedzwiedzw** [tauri-apps/tauri-action#252]
```yaml
      - name: install app dependencies and build it
        run: yarn && yarn build
      - uses: tauri-apps/tauri-action@dev
        with:
          tauriScript: yarn tauri build --target ${{ matrix.target }}
```
produces this
```rust

Run tauri-apps/tauri-action@dev
running yarn [ 'tauri', 'build', '--target', 'i686-pc-windows-msvc', 'build' ]
error: Found argument 'build' which wasn't expected, or isn't valid in this context
```
this feature is needed for building for 32 windows (surprisingly large user base)

**Comment by FabianLars** [comment]
For reference: https://github.com/tauri-apps/tauri-action/blob/dev/packages/core/index.ts#L357

We handle tauriScript in a really weird way currently. Like the usage the readme shows doesn't work.

**Comment by goenning** [comment]
What's the correct usage? 🤔

**Comment by FabianLars** [comment]
@goenning use args (undocumented) instead of tauriScript
```
with:
  args: --target ${{ matrix.target }}
```

**Comment by stevenhansel** [comment]
@FabianLars I guess for now we can update the documentation so people doesn't get confused? Do you mind if I add some notes in the README?

**Comment by FabianLars** [comment]
sure, go ahead!

**Comment by stevenhansel** [comment]
@FabianLars I already opened the PR, but I would like to know what's the real purpose of the `tauriScript` option? I would like to help to fix it.

**Comment by FabianLars** [comment]
At this point i'm not so sure anymore either haha.
In theory it's supposed to do what's described in `Caveats`:
> You can run custom Tauri CLI scripts with the tauriScript option. So instead of running yarn tauri build or npx tauri build, we'll execute ${tauriScript}.
    Useful when you need custom build functionality when creating Tauri apps e.g. a desktop:build script.

But i think we're at a point where we may have to rethink the whole action before trying to fix this.
