### ISSUE TITLE
Parse "../package.json" as app version

### ISSUE THREAD

**Issue by Daniel-Knights** [tauri-apps/tauri-action#262]
The `package.version` field of `tauri.conf.json` supports using `"../package.json"` as a value, so they share the same version. From what I can tell, this package doesn't check if that's the case, [leading to an error in my app's workflow](https://github.com/Daniel-Knights/note-boi/runs/6242361710?check_suite_focus=true#step:7:450):

```bash
   Compiling note-boi v0.1.0 (/Users/runner/work/note-boi/note-boi/src-tauri)
    Finished release [optimized] target(s) in 6m 35s
    Bundling NoteBoi.app
    Bundling "/Users/runner/work/note-boi/note-boi/src-tauri/target/release/bundle/dmg/NoteBoi_0.1.3_x64.dmg"
info: running bundle_dmg.sh
    Bundling "/Users/runner/work/note-boi/note-boi/src-tauri/target/release/bundle/macos/NoteBoi.app.tar.gz"
        /Users/runner/work/note-boi/note-boi/src-tauri/target/release/bundle/macos/NoteBoi.app
        /Users/runner/work/note-boi/note-boi/src-tauri/target/release/bundle/dmg/NoteBoi_0.1.3_x64.dmg
        /Users/runner/work/note-boi/note-boi/src-tauri/target/release/bundle/macos/NoteBoi.app.tar.gz (updater)
    Finished 3 bundles at:
[Signed] 1 updater archive at:
        /Users/runner/work/note-boi/note-boi/src-tauri/target/release/bundle/macos/NoteBoi.app.tar.gz.sig
Artifacts: /Users/runner/work/note-boi/note-boi/src-tauri/target/release/bundle/macos/NoteBoi.app,/Users/runner/work/note-boi/note-boi/src-tauri/target/release/bundle/macos/NoteBoi.app.tar.gz,/Users/runner/work/note-boi/note-boi/src-tauri/target/release/bundle/macos/NoteBoi.app.tar.gz.sig.
Couldn't find release with tag v../package.json. Creating one.
Error: Validation Failed: {"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not a valid tag"}, {"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not well-formed"}, {"resource":"Release","code":"custom","message":"Published releases must have a valid tag"}
```

Have I made a mistake somewhere or is this a feature that needs to be added?

[Relevant YAML file](https://github.com/Daniel-Knights/note-boi/blob/updater/.github/workflows/release.yml).

**Comment by FabianLars** [comment]
> Have I made a mistake somewhere or is this a feature that needs to be added?

You're right, it's not handled correctly. Thx for the report.

**Comment by FabianLars** [comment]
~~Since we didn't actually close this issue i can't re-open it, but just wanted to mention that some people mentioned that the linked PR wasn't enough to fix actually fix the action.~~
The release workflow didn't create the tags...

**Comment by vdvman1** [comment]
So this is fixed now? Do I need to do anything to update my workflow to use the new version of the action?

**Comment by FabianLars** [comment]
As long as you use `tauri-action@v0` or `@dev` it should pull the latest version automatically.
And yes, it's supposedly fixed now, though I didn't test it myself yet tbh.

**Comment by nwesterhausen** [comment]
I have had it working since the merge by using the commit hash: '@<hash>'

I was not have success leaving it at '@v0'

Quick update: After trying '@dev' I have had success.
