### ISSUE TITLE
docs: Install libayatana-appindicator3-dev besides to libappindicator3-dev

### ISSUE THREAD

**Issue by banyudu** [tauri-apps/tauri-action#274]
In the `install dependencies (ubuntu only)` section, there's 

```bash
sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
```

However, it doesn't work when `ayatana-tray` feature is enabled.

```bash
  = note: /usr/bin/ld: cannot find -layatana-appindicator3
```

Should be

```bash
sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev libayatana-appindicator3-dev librsvg2-dev patchelf
```

**Comment by lucasfernog** [comment]
You're right, but we're dropping the ayatana-tray feature in the next release, we'll detect which one to use at runtime (and some build time flags to determine which one to use on the debian depends field / appimage bundling).
