### ISSUE TITLE
Can't build on ubuntu

### ISSUE THREAD

**Issue by Septias** [tauri-apps/tauri-action#277]
I've used one of your templates in my personal repository and have the problem that building on linux crashes because too few artefacts were generated as can be seen here:
![image](https://user-images.githubusercontent.com/39526136/173381562-b2bf9f20-f00f-45f2-90dc-847a9151748c.png)
[This](https://github.com/Septias/reddit_wallpapers/blob/master/.github/workflows/main.yml) is my workflow-file if you're interested. 

Have a great afternoon :-)

**Comment by FabianLars** [comment]
So the issue is that app names get converted to kebab case on linux (`_` -> `-`) and the action doesn't take this into account.

We talked about this exact thing a week ago on discord but didn't file an issue for it since we wanted to fix it that day, and well, we obviously forgot to do that 😂

**Comment by Septias** [comment]
When will this be tackled?

**Comment by FabianLars** [comment]
Soon, sorry for the delay. It will probably be fixed together with #243

**Comment by Septias** [comment]
How is it looking? Any Idea on when a fix gets released?

**Comment by FabianLars** [comment]
When i (or someone else) start working on it :/ I was really busy the last couple of weeks/months; my todo list is growing and growing :sweat_smile:

**Comment by Septias** [comment]
Ah okay, don't bother about it too much then. It really has no priority for me and is only a "nice-tohave" :)
