### ISSUE TITLE
Action failing with Mac notarization errors when we believe we're opting out of it

### ISSUE THREAD

**Issue by SeanKilleen** [tauri-apps/tauri-action#291]
Hi all,

We have a small app, Brancato ([repo link](https://github.com/KilleenCode/brancato)), that is using Tauri. Our builds were working but appear to be failing sometime after April 3 (we haven't released for a while, and just noticed).

The [error we're getting](https://github.com/KilleenCode/brancato/runs/7267266545?check_suite_focus=true#step:9:1836) in our build is:

```
Notarizing /Users/runner/work/brancato/brancato/src-tauri/target/release/bundle/macos/brancato.app
       Error failed to bundle project: failed to upload app to Apple's notarization servers.: failed to upload app to Apple's notarization servers.: `failed to run xcrun`
```

But the issue here, I think, is that _I don't know that we've ever notarized the app in the past_. In fact, I double-checked, and [in our workflow](https://github.com/KilleenCode/brancato/blob/main/.github/workflows/main.yml#L49), we're not supplying the environment variables, such as `APPLE_API_ISSUER` and `APPLE_API_KEY`, that [the docs say](https://tauri.app/ko/v1/guides/distribution/sign-macos/#tldr) is only required if we're notarizing.

I've looked through the docs and issues to see if anything is changed, so apologies if I'm missing something. But is it possible that the process for opting out of notarization has changed in the past ~3 months, or something added/changed that would possibly call this notarization to run when it hadn't before?

I apologize that I can't provide a better comparison; our best successful build was long enough ago that the logs have been deleted so I can't reference them to compare.

Any insight you could provide on this would be incredibly helpful. Thanks!

**Comment by SeanKilleen** [comment]
Note, we are using the Tauri cli 1.0.3 in our latest attempts, so if something major has changed as part of moving to 1.x (congratulations, by the way! 🎉 ), it's possible that I missed it.

**Comment by SeanKilleen** [comment]
Sorry about the red herring on this. It turns out, the issue was that I needed to log into the apple developer portal and accept a new TOS. It was not obvious in any way, and that combined with the docs on notarization led me in the wrong direction. 

Thanks and sorry if you spent any cycles on this!

**Comment by RyKilleen** [comment]
Following up here with the relevant issue that tipped us off, should anyone's search lead them here:

https://github.com/electron/electron-notarize/issues/24
