### ISSUE TITLE
Feature request: Make owner and repo configurable

### ISSUE THREAD

**Issue by robertkern** [tauri-apps/tauri-action#298]
Currently the action will only upload assets to a release in the current repo. My use-case is that i'd like to keep the app code in a private repo and use this action to upload assets to a release in a public repo that I configure (so i can have the app source in a private repo and the binaries in a public repo).

https://github.com/tauri-apps/tauri-action/blob/b2d9983822d6a0f20aaca7543a5e2fc314204159/packages/action/src/upload-release-assets.ts#L36-L37

**Comment by FabianLars** [comment]
Until the action's own upload mechanism supports this (if at all), you can use the last example from our readme which does support that already: <https://github.com/tauri-apps/tauri-action#uploading-the-artifacts-to-a-release>

**Comment by robertkern** [comment]
Thanks for responding. The last example allows creating the draft release and publishing the release in another repo, but the assets upload part only happens inside `tauri-action` (which is hardcoded to `context.repo.owner/repo`)
