### ISSUE TITLE
Error: No artifacts were founded (Windows MSI)

### ISSUE THREAD

**Issue by chlbri** [tauri-apps/tauri-action#299]
I use this config

```- name: Build the app
        uses: tauri-apps/tauri-action@v0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ needs.tag.outputs.tag }}
          releaseName: ${{ needs.tag.outputs.tag }}
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
```
 and I receive as result:

Finished 1 bundle at:
[490](https://github.com/chlbri/tauri-solid/runs/8062655898?check_suite_focus=true#step:12:490)
        D:\a\tauri-solid\tauri-solid\src-tauri\target\release\bundle/msi/tauri-solid_0.1.0_x64_en-US.msi

[492](https://github.com/chlbri/tauri-solid/runs/8062655898?check_suite_focus=true#step:12:492) Error: No artifacts were found.

**Comment by mardukbp** [comment]
Similar to #297 and #240.

**Comment by FabianLars** [comment]
Actually this looks like the issue fixed in https://github.com/tauri-apps/tauri-action/pull/227 - Upgrade your tauri-action dependency to `v0.3` and it should work.

**Comment by dharun-sahaj** [comment]
Updating to 0.3 still gives similar error
```
D:\a\dir_name\dir1\src-tauri\target\release\bundle\msi\desktop_app_0.1.0_x64_en-US.msi
D:\a\dir_name\dir1\src-tauri\target\release\bundle\msi\desktop_app_0.1.0_x64_en-US.msi.zip
D:\a\dir_name\dir1\src-tauri\target\release\bundle\msi\desktop_app_0.1.0_x64_en-US.msi.zip.sig
Error: No artifacts were found.
```

**Comment by chlbri** [comment]
Cool
