### ISSUE TITLE
AppImage file is not uploaded to release (only deb)

### ISSUE THREAD

**Issue by MaKleSoft** [tauri-apps/tauri-action#31]
Workflow file: https://github.com/padloc/padloc/blob/tauri-v3.1.1/.github/workflows/build-tauri-2.yml

**Comment by zicklag** [comment]
I'm having this issue too, but I'm not sure what's wrong as it looks like the code makes an attempt to upload it anyway:

https://github.com/tauri-apps/tauri-action/blob/2dd3c008323a3dacba204946b59c7330c1b880dc/src/main.ts#L190-L193

**Comment by loloof64** [comment]
Hi ! Also having the same issue.

It seems that the produced appimage has not the ${app.version} part in it, and as a consequence it is filtered from the files to deploy (see the filter command some lines below of the source @zicklag has given an excerpt).

So the simplest way would be to rename the appimage first, to include the ${app.version}_${arch} : this can be done in the tauri-action with a call to `fs.renameSync`.

**Comment by loloof64** [comment]
I've just created a pull request : https://github.com/tauri-apps/tauri-action/pull/58

Hoping that my code is fine, as I could not try it.

**Comment by loloof64** [comment]
I've managed to upload deb and appimage at the same time.

For that 
1. I've release a Github Action on the marketplace : https://github.com/marketplace/actions/tauri-action
2. You just have to replace a line in your build.yml : replace `- uses: tauri-apps/tauri-action@v0` with `- uses: loloof64/tauri-action@marketplace_2`.

I hope that can also work on your side.

**Comment by zicklag** [comment]
Awesome, thanks! :smiley:

**Comment by lucasfernog** [comment]
This is an upstream issue, the output file name is wrong. I'll fix it on the tauri bundler.

**Comment by lucasfernog** [comment]
Fixed on the referenced PR, will be available on next Tauri release. We're adding a bunch of new features, so stay tuned :) thanks for the report! And sorry it took me so long to take a look :(
