### ISSUE TITLE
only bundles are upload

### ISSUE THREAD

**Issue by liudonghua123** [tauri-apps/tauri-action#314]
I see this action only upload the bundles(installer), the executable is not configurable to upload.

For example, it only upload `bundles/*.msi` for the windows build, I also want to upload ``join(artifactsPath, `${fileAppName}.exe`)``.

https://github.com/tauri-apps/tauri-action/blob/87ceccdc2e3b936d18cefef2ef03c96361b353ce/packages/core/index.ts#L424-L445

**Comment by FabianLars** [comment]
Duplicate of #302 

Keep in mind that this is _intended_ because the .exe is usually not something you can ship to your users.

**Comment by liudonghua123** [comment]
> Duplicate of #302
> 
> Keep in mind that this is _intended_ because the .exe is usually not something you can ship to your users.

However, `.exe` executable is a green portable app, and the msi installer just wrap the same `.exe` file for windows platform.
