### ISSUE TITLE
The `set-output` command is deprecated ...

### ISSUE THREAD

**Issue by elibroftw** [tauri-apps/tauri-action#319]
I believe when you updated the dependencies you didn't update the dist 

https://github.com/elibroftw/google-keep-desktop-app/actions/runs/3408099945/jobs/5668367270#step:9:494

**Comment by FabianLars** [comment]
The repo's dist files indeed don't include the updates, _but_ my local copy does and it still has set-output usages.

Gonna update it soon-ish either way but there are some typescript issues that need to be resolved first and idk when i have the time for that.

Thanks for the report btw!

**Comment by elibroftw** [comment]
Pretty sure the latest update only has set-output for cases where github runners are still legacy. It took me a couple hours to understand how the update fixes the depreciation warning.
