### ISSUE TITLE
Make it more module-like

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri-action#32]
At the techtalk tonight, there was a proposal to make this more dry by making this more thin, i.e. just do what the tauri action needs, and nothing more. (let the release action be external)

having an implementation example would help

**Comment by lucasfernog** [comment]
The release is optional. Also I've discussed this with Jacob and we agreed that it's good to have the release option since the action ensures the build passes before making a release, simplifying workflows.
