### ISSUE TITLE
Provide an option to disable creating a GitHub release

### ISSUE THREAD

**Issue by kolaente** [tauri-apps/tauri-action#320]
I'd love to use this action to provide unstable / nightly builds of my app which are built based on what is currently on the `main` branch. These builds don't have a tag or release, artifacts are instead uploaded  This is an approach which I already use for the other components of the app. It would be enough if the action supported just disabling the creation of a GitHub release and instead just "outputs" the binaries which I could then attach as build artifacts or upload to s3 or similar.

**Comment by FabianLars** [comment]
This is indeed something i'd like to add in the future, but i'd like to refactor larger parts of the action first so it will take a while.

In the meantime you could look at https://github.com/JonasKruckenberg/tauri-build or you could use no action at all (that's what i use in my own projects for example, where i also upload the artifacts to my own server)

**Comment by FabianLars** [comment]
Looks like i fixed this 3 weeks later in this pr https://github.com/tauri-apps/tauri-action/pull/332. Simply omit `releaseId` and `tagName` and the action will not try to upload anything.
