### ISSUE TITLE
unknown field `useBootstrapper`, expected `depends` or `files`

### ISSUE THREAD

**Issue by Septias** [tauri-apps/tauri-action#323]
Hi, my workflow runs crash with the following error:
```
unknown field `useBootstrapper`, expected `depends` or `files` 
```

This is my workflow file: 
https://github.com/Septias/reddit-wallpapers/blob/master/.github/workflows/main.yml
And this is the crashing run:
https://github.com/Septias/reddit-wallpapers/actions/runs/3419683609/jobs/5693512802

How do I fix that?

Edit: on my machine it builds successfully

**Comment by FabianLars** [comment]
You need to update the tauri cli (in package.json and the lockfile), it's too old.

**Comment by Septias** [comment]
ahhh, I was looking at my Cargo.toml file the whole time sorry. I even saw the other issue.
Can I just delete packag.json and it uses the Cargo.toml?

**Comment by lucasfernog** [comment]
Not really, you need to either install the @tauri-apps/cli package via package.json or rely on global installations.

**Comment by Septias** [comment]
Thats what I  call active development :joy: 1min after Issue creation a response from 2 maintainers. Very good boys, keept it up! :joy: 
Anyway, thank you! :)

**Comment by Septias** [comment]
Now, my bundle only creates 
/home/runner/work/reddit-wallpapers/reddit-wallpapers/src-tauri/target/release/bundle/deb/reddit-wallpapers_0.1.0_amd64.deb
        /home/runner/work/reddit-wallpapers/reddit-wallpapers/src-tauri/target/release/bundle/appimage/reddit-wallpapers_0.1.0_amd64.AppImage

while the action requires:
/home/runner/work/reddit-wallpapers/reddit-wallpapers/src-tauri/target/release/bundle/appimage/reddit_wallpapers_0.1.0_amd64.AppImage
/home/runner/work/reddit-wallpapers/reddit-wallpapers/src-tauri/target/release/bundle/appimage/reddit_wallpapers_0.1.0_amd64.AppImage.tar.gz
/home/runner/work/reddit-wallpapers/reddit-wallpapers/src-tauri/target/release/bundle/appimage/reddit_wallpapers_0.1.0_amd64.AppImage.tar.gz.sig

Is there also an easy fix for that?
ref: https://github.com/Septias/reddit-wallpapers/actions/runs/3420268841/jobs/5694867885

**Comment by FabianLars** [comment]
That's not why it fails. It doesn't need _all_ of these artifacts (the missing ones are because you disabled the updater - which is fine).
The issue here is a bug with `-`/`_` in the file name - this is fixed on dev so you could try `tauri-apps/tauri-action@dev` instead of v0

**Comment by Septias** [comment]
okay, I'll try that

**Comment by Septias** [comment]
Okay, now the runs that formerly worked fail 
https://github.com/Septias/reddit-wallpapers/actions/runs/3420584804/jobs/5695597138

**Comment by FabianLars** [comment]
ah damn, forgot to merge the fix for that. Try again now, sorry

**Comment by Septias** [comment]
I'm sorry that I'm doing this to you, but this here also crashes:
https://github.com/Septias/reddit-wallpapers/actions/runs/3420584804/jobs/5696984401

**Comment by FabianLars** [comment]
hmm, never seen that one, i can't seem to repro that one in my own project but i'll keep looking.
In the meantime you could try to clean the release assets because their names changed on dev

nvm can repro. had to disable the updater.

**Comment by FabianLars** [comment]
i think i fixed it now, can you try again please?
