### ISSUE TITLE
[enhancement] Use CLI to simplify tauri-action usage

### ISSUE THREAD

**Issue by lencx** [tauri-apps/tauri-action#330]
repo: https://github.com/lencx/tauri-release

From the configuration of `tauri action` to the triggering of `github action`, the configuration is cumbersome. I realized one-click publishing through scripts (this version tag will be created every time a version is released).

## Install

```bash
npm i -D @tauri-release/cli
```

## new

```bash
# generate tauri update-log file, the default name is `UPDATE_LOG.md`
tr new log

# generate github action file, the default name is `.github/workflows/release.yml`
tr new action
```

## release

`--git`: Enable the git command to automatically submit after the version is updated, create a tag and push it to the remote repository (`git add -> git commit -> git tag -> git push`)

```bash
# major: 0.x.x -> 1.x.x
# minor: x.0.x -> x.1.x
tr release --[major|minor]

# patch: x.x.0 -> x.x.1
tr release --git
```

## updater

```bash
# generate tauri update file, the default name is `updater/install.json`
tr updater --owner=GITHUB_OWNER --repo=GITHUB_REPO --token=GITHUB_TOKEN
```

## Example

- [lencx/WA/package.json](https://github.com/lencx/WA/blob/main/package.json)
- [lencx/WA/.github/workflows/release.yml](https://github.com/lencx/WA/blob/main/.github/workflows/release.yml)

<img width="419" alt="cli" src="https://user-images.githubusercontent.com/16164244/204541334-560d1c8d-aa59-45fd-a0e8-f27ada461e25.png">

**Comment by FabianLars** [comment]
This _may_ be something for https://github.com/tauri-apps/awesome-tauri/
