### ISSUE TITLE
Generate and upload .sig files for the updater

### ISSUE THREAD

**Issue by jensim** [tauri-apps/tauri-action#331]
# Problem
I want to generate `.sig`-files for the release assets in order to do a complete release train for the updater in my tauri application

# Solution
When you follow the steps over at [tauri.app](https://tauri.app/v1/guides/distribution/updater/) to create updates and sign them, you create a `.sig`-file with the `tauri signer sign -p "$TAURI_KEY_PASSWORD" -v -k "$TAURI_PRIVATE_KEY" "$ASSET"` command
It would be very convenient if this action was able to iterate over the assets and generate+upload `.sig` files..

**Comment by FabianLars** [comment]
It already does it as long as you set up the updater and signing keys. See the screenshot of this PR for example as somewhat proof: <https://github.com/tauri-apps/tauri-action/pull/301> (this is the workflow file btw https://github.com/FabianLars/mw-toolbox/blob/release/.github/workflows/temp.yml - disclaimer: it's used for _testing_ PRs in this repo so it may not be suitable for actual publishing pipelines)

**Comment by jensim** [comment]
I then apologize for the noise I made 🤦
And let me say thank you for a beautiful action and platform to build my ideas ontop of! :-D
