### ISSUE TITLE
When the action uses the Npx action it uses "tauri" instead of "@tauri-apps/cli"

### ISSUE THREAD

**Issue by simonhyll** [tauri-apps/tauri-action#367]
The title is pretty self explanatory. The action will use <https://www.npmjs.com/package/tauri> if it decides to use npx.

Current workaround is to set tauriScript manually and install the CLI manually.

**Comment by FabianLars** [comment]
This should only be an issue if the tauri frontend  project is in a npm workspace right? At least that's the only thing that was reported to me. Of course still an issue, and i'd like to tackle it after https://github.com/tauri-apps/tauri-action/pull/362
