### ISSUE TITLE
.deb malformed archive 

### ISSUE THREAD

**Issue by goldcoders** [tauri-apps/tauri-action#38]
dont know why the workflow produced a malformed .deb archived.
Im using archlinux , so im using debtap to reverse compile .deb to 

<details>
<summary> Output Using Debtap </summary>

```bash
╰ debtap canopus_0.1.1_amd64.deb 
==> Extracting package data... 
ar: /home/uriah/.tauri/canopus_0.1.1_amd64.deb: malformed archive 
ls: cannot access '*': No such file or directory 
ar: /home/uriah/.tauri/canopus_0.1.1_amd64.deb: malformed archive 
==> Fixing possible directories structure differencies... 
==> Generating .PKGINFO file... 
grep: control: No such file or directory 
grep: control: No such file or directory 
grep: control: No such file or directory 
grep: control: No such file or directory 
grep: control: No such file or directory 
grep: control: No such file or directory 
grep: control: No such file or directory 
grep: control: No such file or directory 
grep: control: No such file or directory 
grep: control: No such file or directory 
grep: control: No such file or directory 
grep: control: No such file or directory 
grep: control: No such file or directory 
grep: control: No such file or directory 
:: Enter Packager name: 
^C 
╭─    ~/.tauri                                                                                                                            SIGINT(2)  

```

</details>

but locally when i build and use debtap to install it on my arch laptop it works...

it produces the correct .pkg.tar.zst file

```bash
canopus_0.1.1_amd64  canopus-0.1.1-1-x86_64.pkg.tar.zst
```

then i can install normally 

pacman  - U canopus-0.1.1-1-x86_64.pkg.tar.zst

and i can run canopus then on the command line

![pic-full-200801-0513-00](https://user-images.githubusercontent.com/55337687/89077876-c40dc700-d3b5-11ea-8d12-d5f2f66d297a.png)

maybe there are missing packages when building the deb packages?

also there is no AppImage like...

You can check my repo here [Canopus](https://github.com/goldcoders/canopus)

**Comment by lucasfernog** [comment]
I've tried this on latest and I've managed to run `debtap` successfully (will be available on the next release).

Please reopen if you see this again.
