### ISSUE TITLE
Action not detecting TAURI_PRIVATE_KEY environment variable

### ISSUE THREAD

**Issue by TristanPouliquen** [tauri-apps/tauri-action#391]
Hi, 

I'm trying to use this action to bundle my app for the different main platforms, and trying to add the support for the Tauri updater feature.

I didn't find a code example on how to make it work, but of what I understand, I need to have a `TAURI_PRIVATE_KEY` and `TAURI_KEY_PASSWORD` in the environment when the action runs a `yarn tauri build`.

I have tried to pass my private key as a secret to this action, but my job keeps failing stating that it did not find the `TAURI_PRIVATE_KEY` env variable.

Here is a build example where you can see that the env var is correctly set & not null in the first steps, but still failing on the action run: https://github.com/TristanPouliquen/selection-poste-enm/actions/runs/4293616165/jobs/7481521854

Is there something I am not doing right? 

I'll happily PR a documentation update with a working example once I have found the solution :)

**Comment by FabianLars** [comment]
Are you absolutely sure the secret is set? Maybe just set it again either way (had to do the same in another repo for Tauri unrelated secrets yesterday...).
Because I'm not sure if your env check is actually working the way you expect here.

p.s. the action doesn't do anything with the env vars, the invoked tauri cli gets it from the env just like it would in a local environment.

**Comment by TristanPouliquen** [comment]
Hi again 😁 

I added some steps to my workflow (https://github.com/TristanPouliquen/selection-poste-enm/blob/main/.github/workflows/test_build.yml#L24) to ensure that the secret was correctly set and that `{{ secrets.TAURI_PRIVATE_KEY }}` wasn"t returning an empty string. 

I already tried setting it again just in case 😕 

I added the secrets under my repository > Settings > Secrets & variables > Actions via the new "New repository secret".

As my custom step shows, the value seems readable.

**Comment by FabianLars** [comment]
Yeah I saw that env var check. It's what I meant where i think it may not work as expected. As-in maybe it doesn't count as an empty string if it's not set at all? (Or maybe gh returns something weird if it's not set idk)

There _must_ be something specific to your repo here. The action has too many users for this to be a general problem 🤔

I'll take another look when I'm back home!

**Comment by TristanPouliquen** [comment]
I'll try and dump the secret, I'll rotate the keys afterwards, just in case.

**Comment by TristanPouliquen** [comment]
https://github.com/TristanPouliquen/selection-poste-enm/actions/runs/4295439371/jobs/7485855800

Echoing the `$TAURI_PRIVATE_KEY` logs correctly '***' (Github hides secrets).

Is the message the same if the key were to be invalid?

**Comment by TristanPouliquen** [comment]
If ever, this key works locally to build my Linux bundles & generate the .tar.gz for the updater

**Comment by FabianLars** [comment]
I wonder if gh just check if you access `secrets.` and replaces it no matter if set or not.

Can you try setting the env for the whole job or whole workflow instead of just the step? No idea how that would be different especially since it works on the step for me but worth a try i guess

**Comment by TristanPouliquen** [comment]
I'll try to see! 
I also launched a new run with a newline at the end of the value of my secret, in case.

**Comment by TristanPouliquen** [comment]
I understood my mistake.... Sorry for the inconvenience.

I added the TAURI_PRIVATE_KEY env var to my call to `tauri-apps/tauri-action` but the failure comes in the previous stage where I have a `yarn tauri build` that is there by mistake apparently.

😓

**Comment by FabianLars** [comment]
Oh wow, i didn't notice that either :D
Glad you figured it out!

**Comment by TristanPouliquen** [comment]
Rubber ducking often works! 😅
