### ISSUE TITLE
[bug] Error incorrect updater private key password: Device not configured (os error 6)

### ISSUE THREAD

**Issue by ppbl** [tauri-apps/tauri-action#392]
### Describe the bug

tauri-build = { version = "2.0.0-alpha.1", features = [] }
tauri = { version = "2.0.0-alpha.3", features = ["api-all", "devtools", "updater"] }

tauri-apps/action build fail
The password is empty. However, the previous 1.x version can be successfully built

### Platform and versions

macos runner

**Comment by 1zun4** [comment]
Use `TAURI_SIGNING_PRIVATE_KEY_PASSWORD` instead. It was renamed.

**Comment by pacholoamit** [comment]
I was literally looking at my CI for 3 hours determining why I had this issue

**Comment by thiagovianav** [comment]
> Use `TAURI_SIGNING_PRIVATE_KEY_PASSWORD` instead. It was renamed.

WHY THEY DID THAT OMG.

I SPEND HOURS WITH THAT FUCK IT

**Comment by FabianLars** [comment]
> > Use `TAURI_SIGNING_PRIVATE_KEY_PASSWORD` instead. It was renamed.
> 
> WHY THEY DID THAT OMG.
> 
> I SPEND HOURS WITH THAT FUCK IT

For the next major release I recommend reading the migration guide, this would have apparently saved you hours: https://tauri.app/start/migrate/from-tauri-1/#environment-variables-changes

**Comment by thiagovianav** [comment]
> > > Use `TAURI_SIGNING_PRIVATE_KEY_PASSWORD` instead. It was renamed.
> > 
> > 
> > WHY THEY DID THAT OMG.
> > I SPEND HOURS WITH THAT FUCK IT
> 
> For the next major release I recommend reading the migration guide, this would have apparently saved you hours: https://tauri.app/start/migrate/from-tauri-1/#environment-variables-changes

its not like I migrated, its my first time and I read the guide in plugins.

In the end it was my fault for not paying enough attention writing my .yml

Just ragebait lmao
