### ISSUE TITLE
Vague missing file error

### ISSUE THREAD

**Issue by beckler** [tauri-apps/tauri-action#393]
Running a pipeline with the `dev` branch.

No idea what is causing this, but whenever it gets to the step to run this action, it immediately fails with the following error:

```
Run tauri-apps/tauri-action@dev
  with:
    tagName: v0.8.2
    releaseId: 94022150
    tauriScript: pnpm tauri
    releaseDraft: false
    prerelease: false
    projectPath: .
    configPath: tauri.conf.json
    includeDebug: false
    includeRelease: true
  env:
    PNPM_HOME: /Users/runner/setup-pnpm/node_modules/.bin
    CACHE_ON_FAILURE: false
    CARGO_INCREMENTAL: 0
    GITHUB_TOKEN: ***
    TAURI_PRIVATE_KEY: ***
    TAURI_KEY_PASSWORD: ***
    ENABLE_CODE_SIGNING: ***
    APPLE_ID: ***
    APPLE_PASSWORD: ***
    APPLE_CERTIFICATE: ***
    APPLE_SIGNING_IDENTITY: ***
    APPLE_CERTIFICATE_PASSWORD: ***
Error: ENOENT: no such file or directory, open '/Users/runner/work/Pirate-MIDI-Firmware-Updater/Pirate-MIDI-Firmware-Updater/src-tauri/target/release/build/tauri-api-05d562ed66c85830/out/Cargo.toml'
```

Building locally works just fine, but if I attempt to seek out this particular file **locally**, it doesn't exist, but there is an additional file that says: `Build error: Couldn't find ENV: TAURI_CONFIG or TAURI_DIR`. I'm unsure if this is related.

The frustrating part is that this build has been working, and I'm assuming some change I made broke this, but I have no idea what could of caused it.

**Comment by FabianLars** [comment]
if you remove the `tauri-api` dependency from your cargo.toml file it should _hopefully_ work again.

I'll try to fix it in the action anyway since it's not supposed to search for the tauri config in the target dir at all 🤔 

Edit: Should be fixed now. I still suggest removing the `tauri-api` crate, it's tauri's alpha version.

**Comment by beckler** [comment]
Nice! That did seem to solve my issue! Thank you!
