### ISSUE TITLE
Doesn't build on windows-latest

### ISSUE THREAD

**Issue by icidasset** [tauri-apps/tauri-action#40]
```
    Compiling diffuse v3.0.0-alpha.1 (D:\a\diffuse\diffuse\src-tauri)
    Finished release [optimized] target(s) in 6m 00s
info: Verifying wix package
info: Downloading https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
info: validating hash
info: extracting WIX
info: Target: x64
info: running candle for main.wxs
info: running candle.exe
error: Shell Scripting Error:`error running candle.exe, try running with --verbose to see command output`

 app:spawn Command "cargo" failed with exit code: 1 +1ms

 app:tauri (runner) ⚠️  [FAIL] Cargo CLI has failed +0ms

 app:tauri Shutting down tauri process... +1ms
##[error]Command failed with ENOENT: tauri build
spawn tauri ENOENT
```

_Workflow: https://gist.github.com/icidasset/52c289a08f4a3cd3262a43ca56ce4ae2_

Any ideas?
Thanks! ☺️

**Comment by jbolda** [comment]
I don't think this is an error with the action, but rather an error building your app on windows in general. This feels like a familiar error. Just to double check, what versions are you on? If you don't have a windows box to try this on, is the code available that I could run it?

**Comment by icidasset** [comment]
> If your project doesn't include the Tauri files, we create it at compile time, so if you don't need to use Tauri's API, you can just ship native apps through this Action.

I'm using this action do that :point_up: So no Tauri files/config in my project.
Code can be found here: https://github.com/icidasset/diffuse
Action: https://github.com/icidasset/diffuse/actions?query=workflow%3A%22Build+Native+Version%22

The workflow is using tauri action v0.0.9
https://github.com/icidasset/diffuse/blob/master/.github/workflows/native-build.yml#L146

**Comment by jbolda** [comment]
Hmm, this seems to build fine locally for me. @lucasfernog any ideas?

```shell
❯ tauri build
[tauri]: running build
 app:spawn Running "cargo tauri-bundler --features embedded-server --release" +0ms

   Compiling diffuse v0.1.0 (C:\Users\Jacob\Documents\dev\tauri\diffuse\src-tauri)
   Compiling tauri v0.10.0
    Finished release [optimized] target(s) in 13.19s
info: Target: x64
info: running candle for main.wxs
info: running candle.exe
info: running light to produce C:\Users\Jacob\Documents\dev\tauri\diffuse\src-tauri\target\release\bundle/msi/diffuse_0.1.0_x64.msi
    Finished 1 bundle at:
        C:\Users\Jacob\Documents\dev\tauri\diffuse\src-tauri\target\release\bundle/msi/diffuse_0.1.0_x64.msi

 app:tauri Shutting down tauri process... +1ms
```

**Comment by lucasfernog** [comment]
It seems like the workflow failed because set-env no longer exists. I've updated the README to reflect the new GH Actions API.
