### ISSUE TITLE
latest.json contains data for only one platform

### ISSUE THREAD

**Issue by TristanPouliquen** [tauri-apps/tauri-action#409]
Hello,

I tried using the dev version of the action to generate the `latest.json` file for the updater feature.

Here you can see a release with this file added: https://github.com/TristanPouliquen/selection-poste-enm/releases/tag/v1.0.0

Github Actions run corresponding is: https://github.com/TristanPouliquen/selection-poste-enm/actions/runs/4470413508

When I open this file, I see that there is only data for the linux system, which was the latest job to finish.

I have the impression from the code at https://github.com/tauri-apps/tauri-action/blob/dev/src/upload-version-json.ts#L81 that this file is read, platforms are stored in `versionContent.platforms`, the existing file is deleted, the data for the current system is added and the file is output to the release with everything.

In my logs, I have the output stating "Asset not found for the updater JSON", which happens when no .sig file is found.

However, I have in my release & and my log output the .sig files for each platform.

How could I go around understanding what is not working correctly?

**Comment by FabianLars** [comment]
Can you try running it again? I may have accidentally fixed it in another PR 🤔 At least i can't repro it in my test repo anymore...

**Comment by TristanPouliquen** [comment]
Hello, yes a new run now gives me a correct latest.json file! thanks!
