### ISSUE TITLE
Error: No artifacts were found.  (ubuntu-20.04)

### ISSUE THREAD

**Issue by 1595901624** [tauri-apps/tauri-action#420]
![image](https://user-images.githubusercontent.com/35366425/227762190-3f30bd09-ec96-4f66-ba67-680bd781f886.png)

I had used tauri-action@dev and the error still occurred. 
Also, my project name is non-ascii and I am not sure whether it is causing.

my github action file:  https://github.com/1595901624/gpt-aggregated-edition/blob/master/.github/workflows/publish.yml

**Comment by FabianLars** [comment]
This will be fixed in tauri 1.3: https://github.com/tauri-apps/tauri/pull/5872 - imho it's not worth to add a workaround in tauri-action (since we'd have to detect the used tauri cli version etc)
