### ISSUE TITLE
Windows MSI is Not Understood as an MSI by Windows

### ISSUE THREAD

**Issue by zicklag** [tauri-apps/tauri-action#43]
When building running the generated MSI for my project I get the following error:

![image](https://user-images.githubusercontent.com/25393315/89743197-5709c980-da66-11ea-9e81-126ef7649c36.png)

The workflow is [here](https://github.com/zicklag/juju-lens/blob/master/.github/workflows/main.yml) and the release is [here](https://github.com/zicklag/juju-lens/releases/tag/juju-lens-v0.0.1).

**Comment by jbolda** [comment]
Hmm, nothing jumps out at me as an issue. Are you about to build and install it locally?

**Comment by zicklag** [comment]
I've not gotten that particular error when trying to build on Windows, but I'm unable to get *any* Tauri app to successfully build for windows on any Windows VM ( I'm on Linux myself ) so I'm not sure what the deal is. If there was a Vagrant VM or something that I could use to build for Windows I would gladly use that, but I can't get anything to work. ( https://github.com/tauri-apps/tauri/issues/981 )

**Comment by jbolda** [comment]
Getting the same situation myself, but I was able to build locally. We must have an issue with the action.

https://github.com/jbolda/finatr/releases/tag/finatr-v0.3.0

🤔 I was looking through the code last night and nothing was obviously wrong.

**Comment by zicklag** [comment]
Hmm. Downloading [finatr_0.1.0_x64.msi](https://github.com/jbolda/finatr/releases/download/finatr-v0.3.0/finatr_0.1.0_x64.msi) and trying to install it yields the same issue on my Windows VM:

![image](https://user-images.githubusercontent.com/25393315/90930322-06786180-e3c0-11ea-969d-874cf08e7a45.png)

**Comment by jbolda** [comment]
I upgraded all of my tauri deps, and that did not make a difference. I was able to run the tauri-action script locally, and those worked just fine. It seems to be an issue when it is run within the github action context. Now the issue is figuring out why...

**Comment by zicklag** [comment]
Oh, that's a good sign. The GitHub actions are kind of hard to work with for testing because builds take so long. Maybe we could download a pre-built `tauri-bundler` exe so that it wouldn't have to compile it every time GitHub actions runs?

**Comment by jbolda** [comment]
Oh, that is an interesting idea. Versioning would be interesting though as technically I think this is intended to work with any of the Tauri versions.

**Comment by jbolda** [comment]
Long term I think the intention is to move it into the pipeline as a direct dependency. There is some work in the Rust cache actions to install / download prebuilt binaries instead of building them every time. That might be a better route to pursue I might imagine.

**Comment by jbolda** [comment]
Another update, I built it using the "manual" workflow that we used to use, and that completes just fine. That seems to point at the action having an issue somewhere.

If you need a stopgap, you can see the workflow in this PR: https://github.com/jbolda/finatr/pull/352

**Comment by zicklag** [comment]
> There is some work in the Rust cache actions to install / download prebuilt binaries instead of building them every time. That might be a better route to pursue I might imagine.

Yeah, that's a good idea, then if there are updates they will be compiled, but if nothing changes it shouldn't have to build anything.

> If you need a stopgap, you can see the workflow in this PR: jbolda/finatr#352

Awesome, I'll try that out, thanks. :smiley:

**Comment by jbolda** [comment]
I think it's solved. I pushed a new version of you would like to test it out: https://github.com/tauri-apps/tauri-action/pull/46

**Comment by zicklag** [comment]
Oh, sweet. I'll try it out soon.

**Comment by zicklag** [comment]
Took longer to get to trying this than I though but...It works!!! :tada:

Thanks a lot. I have spent over a month trying to simply get a Windows build of my Tauri application and now I have it. It's a big deal for me. Thanks!
