### ISSUE TITLE
does not support cross-build on mac

### ISSUE THREAD

**Issue by shi-yan** [tauri-apps/tauri-action#430]
I want to build aarch64 artifacts on a x64 builder.

Although I can choose the target by

```yml
 args: --target aarch64-apple-darwin
``` 

and the build was successful,

I get an error saying no expected artifacts are found:

```
darwin/release/bundle/dmg/Epiphany_0.0.0_aarch64.dmg)
     Running bundle_dmg.sh
    Finished 2 bundles at:
        /Users/runner/work/Epiphany/Epiphany/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Epiphany.app
        /Users/runner/work/Epiphany/Epiphany/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/Epiphany_0.0.0_aarch64.dmg

Expected artifacts paths:
/Users/runner/work/Epiphany/Epiphany/src-tauri/target/release/bundle/dmg/Epiphany_0.0.0_x64.dmg
/Users/runner/work/Epiphany/Epiphany/src-tauri/target/release/bundle/macos/Epiphany.app
/Users/runner/work/Epiphany/Epiphany/src-tauri/target/release/bundle/macos/Epiphany.app.tar.gz
/Users/runner/work/Epiphany/Epiphany/src-tauri/target/release/bundle/macos/Epiphany.app.tar.gz.sig
Error: No artifacts were found.
```

because it hard-codes the artifact's name with wrong architecture name:

```
/Users/runner/work/Epiphany/Epiphany/src-tauri/target/release/bundle/dmg/Epiphany_0.0.0_x64.dmg
```

https://github.com/shi-yan/Epiphany/actions/runs/4591230514/jobs/8107255179#step:7:629

**Comment by gschier** [comment]
I just ran into this as well. It would be great to have better support for building and uploading universal binaries.

**Comment by gschier** [comment]
Ah, looks like this is supported in the dev version https://github.com/tauri-apps/tauri-action/issues/356#issuecomment-1379974308

**Comment by FabianLars** [comment]
Correct, it should work in dev.
I'm currently in the process of cleaning up the action for a new release but that needs a bit more time.
