### ISSUE TITLE
Error Invalid byte 45, offset 0.

### ISSUE THREAD

**Issue by NguyenDuck** [tauri-apps/tauri-action#443]
See [Workflow Run](https://github.com/NguyenDuck/editor/actions/runs/4783385258) for more infomation!
Already set up github token, tauri private key, password

**Comment by FabianLars** [comment]
You'll also need to update the pubKey in tauri.conf.json to match your new private key/password.

But i'm not sure if that could cause this error message, but worth a try.

Also, for generating the keys, you did follow this guide, right? <https://tauri.app/v1/guides/distribution/updater>
