### ISSUE TITLE
AWS S3 / Digital ocean spaces

### ISSUE THREAD

**Issue by maddybo** [tauri-apps/tauri-action#483]
How to use this action to upload build to S3?

**Comment by FabianLars** [comment]
Sorry, but that's pretty much completely out of scope of this action, _but_ the action tells you where the assets are via the `artifactPaths` output. To upload the files you can then use that output with whatever S3/DO actions are out there (google should give tons of results for sth like `github action s3`), or a custom nodejs script.

If you do come up with something we'd appreciate if you could share it here for others having the same question :)
