### ISSUE TITLE
BUG: Handling process.arch inconsistency

### ISSUE THREAD

**Issue by louisgv** [tauri-apps/tauri-action#488]
Because this action use https://github.com/tauri-apps/tauri-action/blob/688bc7beb550380b8a4c3542f84d2704312cfe91/src/utils.ts#L225, it is returning the wrong target for Mac M1/M2.

Specifically, M1 and M2 both report process.arch as `arm64` instead of `aarch64`. Thus, the action needed a dedicated target to build for tauri.

I wonder if there's a way to detect M1/M2?...

**Comment by FabianLars** [comment]
Thanks for the report! You're right, the action does not factor in self-hosted runners right now (funnily enough i accidentally made the json uploader work for this so it should only be the actual asset uploader being left)

**Comment by FabianLars** [comment]
I don't have access to (arm64) self hosted runners, could you test the `fix/hosted-runner` branch if you got the time? 🙏

**Comment by louisgv** [comment]
@FabianLars just tested, the fix works :D - thanks so much for the quick PR!

**Comment by FabianLars** [comment]
Thanks for testing!
