### ISSUE TITLE
Change name after build

### ISSUE THREAD

**Issue by maddybo** [tauri-apps/tauri-action#493]
How to change name files with extension .dmg, .msi etc name from Name_version_platform.extension to name.extension?

**Comment by FabianLars** [comment]
Thanks for the requestion! The action currently has no setting for this, so if you need this feature asap you'd have to either clone this action and implement it yourself, or use a different action to upload the release assets.

Also, i'm closing this as a duplicate of https://github.com/tauri-apps/tauri-action/issues/215 :)
