### ISSUE TITLE
How to skip signing when uploading releases

### ISSUE THREAD

**Issue by myrrhkhan** [tauri-apps/tauri-action#494]
I am currently creating a Tauri app as a side project, not intending on making an app I'd like to release on a large scale, so I do not plan on signing my program. I would still, however, like to upload the binaries as releases and stuff.

I've added the YAML files to create a new version and upload the binaries every time I push to main. However, I get the `Signature not found for the updater JSON. Skipping upload...` error, resulting in my binaries not being uploaded.

Any way I can upload my binaries using this action without requiring a signature?

If anyone is interested and needs this, here's the [action output](https://github.com/myrrhkhan/VarEdit/actions/runs/5193347059/jobs/9363773070), and here's the [action itself](https://github.com/myrrhkhan/VarEdit/blob/main/.github/workflows/publish.yaml).

Thanks for the help, am new to GitHub actions, so my apologies.

**Comment by FabianLars** [comment]
> However, I get the Signature not found for the updater JSON. Skipping upload... error

This is not an error. It just tells you what it does basically. In this case you don't have code signing set up so it won't try to upload the updater's json file, but it should still upload other files regardless. This is just to make it easier to spot issues, like if the devs to expect the json file to be uploaded they now know why it isn't for example.

According to the logs it did upload the assets fine, did you check the `/releases` subpage of your repo (<https://github.com/myrrhkhan/VarEdit/releases>)? Draft releases are not visibile on the mainpage untill you publish them.

**Comment by myrrhkhan** [comment]
I did not check the drafts, I see the uploads now. Thank you so much!
