### ISSUE TITLE
Updater latest.json referencing debug builds

### ISSUE THREAD

**Issue by Janaka-Steph** [tauri-apps/tauri-action#498]
If `includeDebug: true` is specified, then the latest.json updater file will reference the debug builds.
I would like to keep having debug builds available in GH releases, but having the updater to select production release builds.

**Comment by FabianLars** [comment]
In case the discord message went under, can you try the `fix/pref-release` branch (instead of v0) please?

**Comment by Janaka-Steph** [comment]
I confirm branch `fix/pref-release` works. Latest.json is listing "production" builds now.  Thanks!

**Comment by FabianLars** [comment]
Thanks for testing!
