### ISSUE TITLE
Can't build tauri 2 on Windows

### ISSUE THREAD

**Issue by bader-nasser** [tauri-apps/tauri-action#539]
I've switched to using tauri 2 but I get this error on windows for both `nsis` and `msi` targets:
> Error failed to bundle project: `unsupported Zip archive: Compression method not supported`

Logs and source code can be found at:
https://github.com/bader-nasser/squh-picu-med-calculator

**Comment by FabianLars** [comment]
This is not a problem with the action but with tauri's cli itself, it was fixed here: https://github.com/tauri-apps/tauri/pull/7296 but not released yet so if you wanna use that you'll either have to use the [cli from git](https://tauri.app/v1/guides/faq#how-can-i-use-unpublished-tauri-changes) or download and unzip the archives [manually](https://github.com/tauri-apps/tauri/issues/7338#issuecomment-1663167373)

**Comment by bader-nasser** [comment]
Thanks
