### ISSUE TITLE
error running candle.exe

### ISSUE THREAD

**Issue by 522247020** [tauri-apps/tauri-action#550]
rust 的版本: rustc 1.71.1 (eb26296b5 2023-08-03)
tauri 的版本: 1.4
winows 的版本: windows 10

我在进行构建的时候发生了错误
我的构建命令:  ` cargo tauri build`

根据其他的问题使用了 `cargo tauri build --verbose` 构建得到的错误如下

错误描述:
```shell
     Running [tauri_bundler::bundle::windows::msi::wix] candle for "main.wxs"
     Running [tauri_bundler::bundle::common] Command `C:\Users\Administrator\AppData\Local\tauri/WixTools\candle.exe  -arch x64 main.wxs -dSourceDir=C:\Users\AdmWindows Installer XML Toolset Compiler version 3.11.2.4516
Copyright (c) .NET Foundation and contributors. All rights reserved.
main.wxs
C:\Users\Administrator\Desktop\rst\mhwy\src-tauri\target\release\wix\x64\main.wxs(12) : error CNDL0006 : The Product/@Manufacturer attribute's value cannot be an       Error [tauri_cli] failed to bundle project: error running candle.exe
```

我根据错误描述，查看 `main.wxs` 文件，发现 `Manufacturer` 的值确实是空的，但是我无法修改他。

```xml
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
    <Product
            Id="*"
            Name="mhwy"
            UpgradeCode="6f623a39-84f7-5d51-89b2-0c18733b7af9"
            Language="!(loc.TauriLanguage)"
            Manufacturer=""
            Version="0.0.0">

```

**Comment by 522247020** [comment]
I made an error while building
My build command:  `cargo tauri build`
Using the `cargo tauri build --verbose` build based on other problems results in the following error
Error description:


I looked at the `main.wxs` file against the error description and found that the Manufacturer value was indeed empty, but I couldn't change it.

**Comment by FabianLars** [comment]
You can configure this value in tauri.conf.json with this property: https://tauri.app/v1/api/config/#bundleconfig.publisher - alternatively it falls back to the middle part of your bundle.identifier config (example `de.fabianlars.my-app` -> `fabianlars`)

**Comment by 522247020** [comment]
Thanks, adding content in `taur.conf.json` -> `Taur.bundle.identifier` solves this problem
