### ISSUE TITLE
[bug] Workspace version not supported, prints [object Object] to file names

### ISSUE THREAD

**Issue by tr3ysmith** [tauri-apps/tauri-action#557]
When using Tauri in a workspace, and the version comes from the Workspace's Cargo.toml, the action ends up processing `version = { workspace = true }` to the filenames and this results in [object Object] being printed.

Ultimately we need to add workspace support to the toml reading. and catch if version is `workspace = true` and then traverse up in directories to get the Workspace's toml file.

**Comment by tr3ysmith** [comment]
@FabianLars Do you mind taking a look at my pull request? It doesn't seem to have fixed the issue, but anytime I do a build using the action, it takes about 45 min due to the size of our app, Is there an easier way to test this locally so I don't eat up all of our Action minutes?

**Comment by FabianLars** [comment]
> Do you mind taking a look at my pull request?

I'm back from vacation tomorrow :)

> Is there an easier way to test this locally

Not reallyyy, i sometimes copy it in a normal .js file so i can run it in nodejs but generally local reproductions never match the runner behavior somehow so i always end up (ab)using a public project of mine (open source projects don't use build minutes) for tests.
