### ISSUE TITLE
Missing GDK3 on Ubuntu 22.04

### ISSUE THREAD

**Issue by daemontus** [tauri-apps/tauri-action#578]
When using `ubuntu-22.04` github action runners, I'm seeing the following error (I am using the recommended script in the repository README):

```
error: failed to run custom build command for `gdk-sys v0.15.1`
error: could not find system library 'gdk-3.0' required by the 'gdk-sys' crate
```

Full run available [here](https://github.com/sybila/biodivine-aeon-desktop/actions/runs/6468740742/job/17561361377).

I'm guessing the "install dependencies (ubuntu only)" part of the example needs to be updated with some additional packages. I'm planning to investigate what is the correct set of dependencies for Ubuntu 22.04 at some point, but if somebody already knows, feel free to share.

I'm guessing this is not critical until Ubuntu 20.04 becomes obsolete, but it might be useful to update the example to the latest version sooner than later :)

**Comment by FabianLars** [comment]
The dependencies shown in the readme are the same for ubuntu 20.04 and 22.04 (still recommended to use 20.04 if you want to support users with systems older than 22.04).

Your repo is private so i can't see the logs and the only thing i could think of without seeing the logs would be that the `if: ` line still checks for 20.04 or is incorrect in some other way.

**Comment by daemontus** [comment]
Apologies, forgot about the repo visibility. Should be public now. 

Anyway, you are right... complete "brain fart" on my side. I read the condition as checking "if runs on ubuntu, install dependencies", not "if runs on ubuntu **20.04**, install dependencies". Of course it works now if I change the version number in the condition. 

Anyways... my bad, thank you!
