### ISSUE TITLE
Error failed to bundle project: Finished with status Invalid for id ...

### ISSUE THREAD

**Issue by chen-rn** [tauri-apps/tauri-action#584]
```
    Finished release [optimized] target(s) in 11m 19s
    Bundling steno.app (/Users/runner/work/steno/steno/src-tauri/target/release/bundle/macos/steno.app)
     Signing with identity "***"
        Info setup keychain from environment variables...
        Info Signing app bundle...
     Signing /Users/runner/work/steno/steno/src-tauri/target/release/bundle/macos/steno.app/Contents/MacOS/steno
     Signing /Users/runner/work/steno/steno/src-tauri/target/release/bundle/macos/steno.app
     Signing with identity "***"
        Info setup keychain from environment variables...
        Info Signing app bundle...
     Signing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/.tmpZq2D5G/steno.zip
  Notarizing /Users/runner/work/steno/steno/src-tauri/target/release/bundle/macos/steno.app
       Error failed to bundle project: Finished with status Invalid for id 8108c3d3-5e55-4d1e-b265-28d2152b1530 (Processing complete)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This occurs during the final stage of the build.
I've tripple checked the code signing process as it seems fine.

Anyone know what status Invalid is?

**Comment by FabianLars** [comment]
iirc this was solved on [discord](https://discord.com/channels/616186924390023171/1164359758069907487) - This [PR](https://github.com/tauri-apps/tauri/pull/7974) is somewhat related because it improves the error message.

**Comment by kjxbyz** [comment]
@FabianLars Is there any solution?

**Comment by FabianLars** [comment]
I'm not quite sure what the specific solution was, but in a more general sense, this `Invalid for id` error afaik means that apple rejected your app. The linked PR will improve that error message and tries to show the reason (as given by apple). You can do the same by running `xcrun notarytool log $ID --key-id $KEYID --key $KEYPATH --issuer $ISSUER`.
