### ISSUE TITLE
Portable windows build

### ISSUE THREAD

**Issue by Milo123459** [tauri-apps/tauri-action#59]
Hello, can we get an example of how to make a portable windows build? So you can download the exe without having to run the MSI.

Thank you.

**Comment by lucasfernog** [comment]
Tauri requires an installer if you define app resources, external binaries or running on environments that do not have Webview2 runtime installed. So I don't think it's a good idea to have a "portable" option since a Tauri binary itself isn't 100% portable.

**Comment by KaKi87** [comment]
Why is it possible to have `AppImage` on Linux but not `.exe` on Windows ?

**Comment by vegardbb** [comment]
An app image basically bundles together all of its dependecies under one cohesive executable unit. A Windows executable file does not necessarily do the very same thing. I'll chalk this up to a difference between platform interfaces.

**Comment by pjdon** [comment]
When building for Windows 10, the .msi installer can be quite small (~2MB for a basic app). Does that contain everything the app needs to install on a Windows 10 machine or does it pull anything from the internet?

I'm wondering if instead of a traditional installer that requires admin permissions, the app could transparently install the necessary dependencies into Appdata instead. I suspect this wouldn't be helpful for a large app with lots of dependencies, but for smaller apps this could be useful in reducing friction with the user, both by eliminating superflous install screen and the need to provide admin privileges.

Is this theoretically possible with Tauri?

**Comment by FabianLars** [comment]
The .msi does indeed download something from the internet - the WebView2 installer if it's not present on the system already.

An installer that does not require admin privileges will be part of v1.3 with the new nsis target - luckily webview2 does have an user-wide install mode too for quite some time now.

**Comment by yuripourre** [comment]
@Milo123459 the I think the Tauri v2 added a portable setup. They are calling it offlineInstaller. I haven't tested myself but will try soon!

https://v2.tauri.app/distribute/windows-installer/#offline-installer

Although this is a BIG deal I didn't see any announcement.

**Comment by abdedarghal111** [comment]
Still not planned portable version?

If it is not, there is any way to create one from scripts or anything?

**Comment by FabianLars** [comment]
the next tauri-action release will be able to upload the binaries via #1141 / #1143 but of course that doesn't change tauri's lackluster support for portable builds 🤷

**Comment by Alex6357** [comment]
Should we consider adding an installer-like shim within the Tauri application to automatically handle (or at least prompt users to install) dependencies?

**Comment by FabianLars** [comment]
It already has that on Windows. But iirc it'll send users to the download page for them to download it themselves. I don't think we'd add more than that to tauri.

**Comment by KaKi87** [comment]
Keeping it at that would be not user-friendly.

**Comment by FabianLars** [comment]
Well it is what it is. Most users have it installed nowadays anyway. If you want more than that it's only a couple of lines. We just can't really do something more intrusive in tauri itself because the webview2 installation process itself is honestly quite terrible (mainly cause it takes ages).

Even the download dialog we have now was a bit controversial but it's meant as a last resort (again, we do not directly support portable builds, whether you and us like it or not)

**Comment by KaKi87** [comment]
> the webview2 installation process itself is honestly quite terrible (mainly cause it takes ages).

Same with Java and .NET, yet all it takes is a warning and a progress bar.

**Comment by FabianLars** [comment]
Which the webview installer has built-in as well. For what it's worth, in those ecosystem the GUI frameworks also don't have a built-in dependency installers, if we count the runtime and the webview as a similar thing here (ignoring that java apps nowadays typically just ship the whole jre with their app directly)

But again, we do not support portable apps. If we were then of course it would look a bit different...

P.S. here's a super old example - still uses the old winreg crate and not sure if the link is correct but I had this on disk still from early v1

```rs
#[cfg(windows)]
use winreg::{
    enums::{HKEY_CURRENT_USER, HKEY_LOCAL_MACHINE},
    RegKey,
};

fn main() -> Result<()> {
    #[cfg(windows)]
    if RegKey::predef(HKEY_LOCAL_MACHINE).open_subkey("SOFTWARE\\WOW6432Node\\Microsoft\\EdgeUpdate\\Clients\\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}").is_err() // System-wide 64bit
      && RegKey::predef(HKEY_LOCAL_MACHINE).open_subkey("SOFTWARE\\Microsoft\\EdgeUpdate\\Clients\\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}").is_err() // System-wide 32bit
      && RegKey::predef(HKEY_CURRENT_USER).open_subkey("SOFTWARE\\Microsoft\\EdgeUpdate\\Clients\\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}").is_err() // User-wide 64bit&32bit
      {
        // WebView2 is not installed.
        let installer = reqwest::blocking::get("https://go.microsoft.com/fwlink/p/?LinkId=2124703")?.bytes()?;
        let path = std::env::temp_dir().join("MicrosoftEdgeWebview2Setup.exe");
        if std::fs::write(&path, installer).is_ok() {
            let mut command = Command::new("powershell.exe");
            command.arg(path);
            command.arg("/install");
            let _ = dbg!(command.output()); // Do some error handling here instead of ignoring it.
        }
      }

    tauri::Builder::default().run(tauri::generate_context!()).expect("error while running tauri app");
}
```
