### ISSUE TITLE
Is this a bug, or a configuration I'm missing?

### ISSUE THREAD

**Issue by naps62** [tauri-apps/tauri-action#623]
I spent way too long figuring out a bug in my releases today: https://github.com/iron-wallet/iron/pull/537

TL;DR: due to unrelated changes, I changed my Cargo.toml in the following way:

```diff
[workspace]
- members = ["bin/iron", "crates/*"]
+ members = ["bin/*", "crates/*"]
```

even though I still only had one binary crate `bin/iron`, this confused the action. instead of looking for artifacts in `target/release/bundle`, it was now looking into `bin/iron/target/release/bundle`, which was obviously empty

not sure if this is a config I'm missing (looked through the readme, but nothing caught my eye), or potentially a bug here

**Comment by FabianLars** [comment]
Oof that's a wild one. Thanks for reporting it! The issue is simply that the pattern is not resolved when it checks if this is the tauri app's workspace root (it compares the member config path to the tauri dir path). I'll push a fix in a few :)

**Comment by FabianLars** [comment]
If you wouldn't mind, could you test the `fix/member-patterns` branch? To do this, simply replace `tauri-apps/tauri-action@v0` with `tauri-apps/tauri-action@fix/member-patterns`

**Comment by naps62** [comment]
certainly. running here already: https://github.com/iron-wallet/iron/actions/runs/7020337087
the whole build should take 5 to 10 minutes

**Comment by naps62** [comment]
Look like the result was the same:

```
Finished 2 bundles at:
        /home/runner/work/iron/iron/target/release/bundle/deb/iron_1.3.0_amd64.deb
        /home/runner/work/iron/iron/target/release/bundle/appimage/iron_1.3.0_amd64.AppImage

Looking for artifacts in:
/home/runner/work/iron/iron/bin/iron/target/release/bundle/deb/iron_1.3.0_amd64.deb
/home/runner/work/iron/iron/bin/iron/target/release/bundle/appimage/iron_1.3.0_amd64.AppImage
/home/runner/work/iron/iron/bin/iron/target/release/bundle/appimage/iron_1.3.0_amd64.AppImage.tar.gz
/home/runner/work/iron/iron/bin/iron/target/release/bundle/appimage/iron_1.3.0_amd64.AppImage.tar.gz.sig
```

**Comment by FabianLars** [comment]
Apologies, that was more of a pain to figure out than expected. Can you try again please?

**Comment by naps62** [comment]
@FabianLars seems good now:

```
    Finished 2 bundles at:
        /home/runner/work/iron/iron/target/release/bundle/deb/iron_1.3.0_amd64.deb
        /home/runner/work/iron/iron/target/release/bundle/appimage/iron_1.3.0_amd64.AppImage
["bin/*","crates/*"]
["bin/iron","crates/abis","crates/args","crates/broadcast","crates/connections","crates/crypto","crates/db","crates/dialogs","crates/exchange-rates","crates/forge","crates/http","crates/networks","crates/rpc","crates/settings","crates/simulator","crates/sync","crates/tracing","crates/types","crates/wallets","crates/ws"]
Looking for artifacts in:
/home/runner/work/iron/iron/target/release/bundle/deb/iron_1.3.0_amd64.deb
/home/runner/work/iron/iron/target/release/bundle/appimage/iron_1.3.0_amd64.AppImage
/home/runner/work/iron/iron/target/release/bundle/appimage/iron_1.3.0_amd64.AppImage.tar.gz
/home/runner/work/iron/iron/target/release/bundle/appimage/iron_1.3.0_amd64.AppImage.tar.gz.sig
Found artifacts:
/home/runner/work/iron/iron/target/release/bundle/deb/iron_1.3.0_amd64.deb
/home/runner/work/iron/iron/target/release/bundle/appimage/iron_1.3.0_amd64.AppImage
```

**Comment by FabianLars** [comment]
awesome, thanks for testing!
