### ISSUE TITLE
Linux Packaging helper (arch, rhel)

### ISSUE THREAD

**Issue by 0-don** [tauri-apps/tauri-action#639]
Hey everyone,

I'm excited to share a tool I've created – the DEB Converter. It's designed to help with distributing Rust Tauri applications across various Linux distributions. This tool automates the conversion of `.deb` packages into other formats like `.pkg.tar.zst` for Arch Linux and `.rpm` for RHEL-based systems.

The DEB Converter integrates seamlessly with GitHub Actions, making it ideal for automating your build and release workflows for Rust Tauri projects.

[Check it out here: ](https://github.com/don-cryptus/linux-packing-pipeline)

As an example of its application, take a look at this [repository](https://github.com/don-cryptus/clippy): 

Feel free to explore, use it in your projects, and share any feedback or questions you might have!

Cheers!

**Comment by wscourge** [comment]
@0-don the link is 404. Did you stop maintaining it?

**Comment by 0-don** [comment]
@wscourge refer to my project which has it implemented https://github.com/0-don/clippy in github action

EDIT:
I reuploaded it
https://github.com/0-don/linux-packing-pipeline
