### ISSUE TITLE
After configuring code signing, local packaging is normal, but packaging using tauri-apps/tauri-action fails.

### ISSUE THREAD

**Issue by kjxbyz** [tauri-apps/tauri-action#689]
After configuring code signing, local packaging is normal, but packaging using tauri-apps/tauri-action fails.

[github action](https://github.com/cyf/faforever-next/actions/runs/7679165196/job/20929884206)

**Comment by izyuumi** [comment]
I am also having the same issue.

**Comment by FabianLars** [comment]
Please try it with `args: --verbose` and post the new error logs.

Most of the time this simply means that the env vars / secrets were set up incorrectly so please double check them.

**Comment by izyuumi** [comment]
It seems like I am missing something in the keychain. Do you know what it is I'm missing?
![CleanShot 20240201 163112](https://github.com/tauri-apps/tauri-action/assets/36561306/208a6ce8-5be3-4da6-8aff-22e7310f3cde)

**Comment by FabianLars** [comment]
hmm, since the signing step and not the notarization is failing it should be on of `APPLE_SIGNING_IDENTITY`, `APPLE_CERTIFICATE`, or `APPLE_CERTIFICATE_PASSWORD` that's somehow wrong.

**Comment by izyuumi** [comment]
I will try to re-set those values.

**Comment by izyuumi** [comment]
I am getting a new error message after re-setting up `APPLE_SIGNING_IDENTITY`, `APPLE_CERTIFICATE`, and `APPLE_CERTIFICATE_PASSWORD`.
![CleanShot 20240202 120217](https://github.com/tauri-apps/tauri-action/assets/36561306/87196441-c337-4663-a4c3-d8b7a734b2a9)

**Comment by izyuumi** [comment]
@kjxbyz Were you able to fix this issue?

**Comment by kjxbyz** [comment]
@izyumidev No, I've given up

**Comment by izyuumi** [comment]
So, I was able to successfully compile and release the app (https://github.com/izyumidev/LAME/releases/tag/v0.0.1-alpha.1) after going through the key creation processes again. However, I tried implementing the [updater](https://tauri.app/v1/guides/distribution/updater) on my app, then I get the error shown in the screenshot below. This error can also be seen in [LAME](https://github.com/izyumidev/LAME/actions/runs/8162269692/job/22312891889). The build workflow is [here](https://github.com/izyumidev/LAME/blob/main/.github/workflows/build.yml) and the Tauri config file is [here](https://github.com/izyumidev/LAME/blob/main/src-tauri/tauri.conf.json). Would someone be able to help me fix this?

![CleanShot 20240305 200744@2x](https://github.com/tauri-apps/tauri-action/assets/36561306/6497d732-a54e-4037-a58e-2e17779ec3db)

**Comment by FabianLars** [comment]
Hmm, in my experience "invalid byte" errors usually meant that the the private key was broken (like, only half of the actual content, or a file path instead of the actual content of the private key). But i also never saw a pubkey with a % in it before so maybe that's the issue 🤔

**Comment by izyuumi** [comment]
You were right, I copied the public key with `%` at the end, which was causing the issue. Thank you!
