### ISSUE TITLE
productName compatibility with Tauri 2 beta 

### ISSUE THREAD

**Issue by dan-nadler** [tauri-apps/tauri-action#701]
Forgive me if any of my terminology is off, I'm pretty new to rust...

In Tauri 2.x, the config file appears to have changed. For this issue, the notable change is that `productName` is now a top-level item instead of being nested underneath `package`.

This results in the following error when the action tries to locate the artifacts if a `productName` is set in `tauri.conf.json`. Note that the action is looking for a file named `tortoise-native*` when it should be looking for `The Tortoise*`

In this case, my crate is named `tortoise-native` and my `productName` is `The Tortoise`.
```
...
    Finished 2 bundles at:
        /Users/<USERNAME>/code/actions-runner/_work/tortoise-native/tortoise-native/src-tauri/target/universal-apple-darwin/release/bundle/macos/The Tortoise.app
        /Users/<USERNAME>/code/actions-runner/_work/tortoise-native/tortoise-native/src-tauri/target/universal-apple-darwin/release/bundle/dmg/The Tortoise_0.7.0_universal.dmg
Looking for artifacts in:
/Users/<USERNAME>/code/actions-runner/_work/tortoise-native/tortoise-native/src-tauri/target/universal-apple-darwin/release/bundle/dmg/tortoise-native_0.7.0_universal.dmg
/Users/<USERNAME>/code/actions-runner/_work/tortoise-native/tortoise-native/src-tauri/target/universal-apple-darwin/release/bundle/macos/tortoise-native.app
/Users/<USERNAME>/code/actions-runner/_work/tortoise-native/tortoise-native/src-tauri/target/universal-apple-darwin/release/bundle/macos/tortoise-native.app.tar.gz
/Users/<USERNAME>/code/actions-runner/_work/tortoise-native/tortoise-native/src-tauri/target/universal-apple-darwin/release/bundle/macos/tortoise-native.app.tar.gz.sig
```

This seems to be the code of interest:
https://github.com/tauri-apps/tauri-action/blob/4bb1df96ee90cc64b4315bfaf82f4fe70d9d521e/src/utils.ts#L281-L289

I'm not sure what your plans are for 2.x support, but one easy way to address this particular issue would be to add  an additional `if` to cover this case. Specifically, check the top level of `config` for `productName` (and likely other variables as well).

I'm happy to make a PR, but wanted to check before I went ahead with anything.

**Comment by FabianLars** [comment]
Hi, thanks for reaching out. There's already a PR from another community member. I meant to finish it up yesterday but there was an emergency. I hope I can do it today or tomorrow, sorry for the inconvenience.

**Comment by dan-nadler** [comment]
Oh great, thanks!

**Comment by FabianLars** [comment]
Just fyi, i am completely offline over the weekend so i will wait with the release until sunday/monday (in case i broke something). If you can't wait so long please use `tauri-apps/tauri-action@dev` or `tauri-apps/tauri-action@81921ba9d3c8163235d21b262dd0c3ad3fb19029` until then.
