### ISSUE TITLE
No artifacts were found.

### ISSUE THREAD

**Issue by BTMuli** [tauri-apps/tauri-action#705]
https://github.com/BTMuli/TeyvatGuide/actions/runs/7843982070/job/21406013841

![image](https://github.com/tauri-apps/tauri-action/assets/72692909/1fd7bae6-f003-4280-9995-4bab32f8feb4)

**Comment by FabianLars** [comment]
Thanks for the report!! Good thing I postponed the release until Sunday/Monday...

I will take a look at it as soon as possible once I'm back home from the hospital :)
Apologies for the inconvenience.
