### ISSUE TITLE
Ubuntu build doesn't work.

### ISSUE THREAD

**Issue by dezoito** [tauri-apps/tauri-action#719]
First Tauri project (and first time using gh actions) so please bear with me.

I'm using [this workflow file](https://github.com/dezoito/ollama-grid-search/blob/main/.github/workflows/publish.yml) which is just a slight variation of the one in the usage example.

After the action runs for all platforms, the artifacts can be downloaded from the repository "releases" page, but:

1- The downloadable for Ubuntu ( ollama-grid-search_0.0.0_amd64.deb ) installs, but nothing happens when you run it, like it quits immediately... the appimage version runs fine, though.

More info:
- The app runs if I manually build it on my local machine (Ubuntu 22.04)
- The appimage file size is 72 Mb (and pretty close to the runable binary), but the deb file is only 4.5Mb (not sure if that matters)
- Haven't tested the windows or mac installs yet.

I would greatly appreciate any help and instructions in case I am missing something here. Thank you!

**Comment by FabianLars** [comment]
Hi, can you try starting the app from inside a terminal? Basically just type `ollama-grid-search` into the terminal (should work after installing it via the deb).

I hope this will give you some error message.

**Comment by dezoito** [comment]
It threw this error:

```sh

ollama-grid-search: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

```

**Comment by FabianLars** [comment]
Here's the summary i gave on this error: https://github.com/tauri-apps/tauri/issues/4470#issuecomment-1170342732 - you can try adding the `"native-tls-vendored"` feature flag to the tauri dependency in cargo.toml

**Comment by dezoito** [comment]
TY!

Edited cause I'm a dummy ;)

**Comment by dezoito** [comment]
No go, @FabianLars ,
```sh
error: failed to select a version for the requirement `wasm-streams = "^0.4"`
candidate versions found which didn't match: 0.3.0, 0.2.3, 0.2.2, ...
location searched: crates.io index
required by package `reqwest v0.11.24`
    ... which satisfies dependency `reqwest = "^0.11.22"` (locked to 0.11.24) of package `ollama-rs v0.1.7`
    ... which satisfies dependency `ollama-rs = "^0.1.7"` (locked to 0.1.7) of package `grid-search-desktop v0.0.1-alpha (/home/xxxx/desenv/ollama-grid-search/src-tauri)`
perhaps a crate was updated and forgotten to be re-vendored?
error: script "tauri" exited with code 101
```
I understand that this is not this project's fault and appreciate the effort... I guess I'll just add a note for Linux users to use the `.deb` only if they are using Ubuntu > 22.04 (unless anybody else chines in with a solution).

**Comment by FabianLars** [comment]
Ahhh, i see, your project doesn't even enable any tauri feature that pulls in reqwest, so it makes sense this didn't help.

The rustls workaround would still be worth a try if you didn't try it already.

```toml
ollama-rs = { version = "0.1.7", default-features = false, features = ["rustls"] }
```

**Comment by dezoito** [comment]
Thanks man. I'll give this a try.

For anyone else reading, I can confirm that the installers work on Windows, Mac, and on older Ubuntu versions.

**Comment by dezoito** [comment]
@FabianLars, that works... thanks a ton!
