### ISSUE TITLE
Tauri v2 failed to build on Ubuntu

### ISSUE THREAD

**Issue by A-kirami** [tauri-apps/tauri-action#720]
It can be built normally on Windows and macos, but failed on Ubuntu.

```log
The following warnings were emitted during compilation:

warning: javascriptcore-rs-sys@1.1.1: 

error: failed to run custom build command for `javascriptcore-rs-sys v1.1.1`

...

  The system library `javascriptcoregtk-4.1` required by crate `javascriptcore-rs-sys` was not found.
  The file `javascriptcoregtk-4.1.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.

  HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `javascriptcoregtk-4.1.pc`.
```

I think it's possible that this part of readme is outdated.

```yaml
- name: install dependencies (ubuntu only)
  if: matrix.platform == 'ubuntu-20.04'
  run: |
    sudo apt-get update
    sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev
```

But I don't quite understand Ubuntu, how should I make modifications to successfully build it?

**Comment by FabianLars** [comment]
The readme is still for Tauri v1. For v2 you have to change all instances of `ubuntu-20.04` to `ubuntu-22.04` and `libwebkit2gtk-4.0-dev` to `libwebkit2gtk-4.1-dev`

**Comment by A-kirami** [comment]
Thank you, the problem has been resolved. I suggest updating readme to add special instructions for v2.

**Comment by caoccao** [comment]
There seems not to be libwebkit2gtk-4.1-dev on Ubuntu 20.04. And this [search result page](https://launchpad.net/+search?field.text=libwebkit2gtk-4.1-dev&field.actions.search=Search) also shows no packages for Ubuntu 20.04.

![image](https://github.com/user-attachments/assets/995f4f77-89a5-4151-b766-5add323d54aa)

**Comment by FabianLars** [comment]
which is why i said to use ubuntu 22.04 :) it's the first version that received 4.1
