### ISSUE TITLE
Ubuntu build fails with `glib-2.0` required by crate `glib-sys`

### ISSUE THREAD

**Issue by dxlbnl** [tauri-apps/tauri-action#753]
I'm not sure why this happens, havent found anything about it regarding actions online. Only someone with an outdated rust setup. 

I've got it building locally, but in the action it fails on the ubuntu build:

https://github.com/wolbodo/bifrost/actions/runs/8552800430/job/23434669313#step:8:577

I've followed the docs. It is a tauri@2 app.

**Comment by FabianLars** [comment]
You forgot to update the matrix in your last commits https://github.com/tauri-apps/tauri-action/blob/dev/examples/publish-to-auto-release.yml#L17-L26
