### ISSUE TITLE
matrix does not support settings

### ISSUE THREAD

**Issue by ezra-en** [tauri-apps/tauri-action#769]
not sure if something changed with how GH actions works, but `settings:` no longer works with matrix. Replacing `settings:` with `include:` effectively does the same thing, but any of the ` ${{ matrix.settings.platform }}` must be changed to `${{ matrix.platform }}` (removing `settings`)

**Comment by FabianLars** [comment]
In what way does it not work? Do you have a source (like an announcement) or any kind of error? I still use it just fine in my workflows.

That said, i misunderstood the docs about `include` and looking at your workflow runs i think i'd prefer it either way 🤔

**Comment by ezra-en** [comment]
Hey Fabian! Glad to see you here! I got errors when copying + pasting the examples into my workflow.yml. Here's an example: 
![image](https://github.com/tauri-apps/tauri-action/assets/7076802/8fc8ea1b-47fe-44a3-90af-d6c44aa90e48)
![image](https://github.com/tauri-apps/tauri-action/assets/7076802/5d0165c9-7d0d-45ce-a548-3417b6088031)

**Comment by ezra-en** [comment]
I would've loved to have some sort of announcement, but I can't seem to find anything. Going back into the docs, since they break out the sections into individual `.md`s, there isn't an easy way to go back in time to see when `settings:` fell out of favour.

**Comment by ezra-en** [comment]
I went all the way back to 2022, and `settings:` isn't mentioned at all in the matrix docs? Where is `settings:` documented? I can't find it even when [searching across the whole repo.](https://github.com/search?q=settings%3A+user%3Agithub+repo%3Agithub%2Fdocs+path%3A*.md&type=code&ref=advsearch)

**Comment by FabianLars** [comment]
Oh right, the editor always complained about this, but only the editor (and idk vscode plugins sometimes) but in the run it actually works.

Technically the error isn't even correct because `include` is not a primitive yml value either x)

**Comment by FabianLars** [comment]
Also to be clear, `settings` is not a special word, it could be `configs` or whatever too.

**Comment by ezra-en** [comment]
Hmm, correct. However, since `include:` appears to be treated as a special case that collapses the available choices into the matrix, I figure it would be a good idea to change things out to `include:` anyway since it also gets rid of the error and is functionally identical? Pretty interesting that the run works anyway, got me quite confused because it doesn't seem like it should work matrix-wise at all according to the docs :joy:

**Comment by FabianLars** [comment]
> I figure it would be a good idea to change things out to include: anyway since it also gets rid of the error and is functionally identical?

already agreed to that in my first message:
> That said, i misunderstood the docs about include and looking at your workflow runs i think i'd prefer it either way 🤔

> got me quite confused because it doesn't seem like it should work matrix-wise at all according to the docs 😂

To be fair, i think those docs are a bit, let's say, suboptimal overall. And we've even used the `settings` object before the docs existed in that capacity lol.

Anyway, i don't have time to do this anytime soon (especially since i consider this low prio), so i'd appreciate if you'd open a PR for the readme and example files. No problem if you don't have time either :)

**Comment by ezra-en** [comment]
no prob! will get a PR done within the week :)
