### ISSUE TITLE
[Feature Request] Is there a way to build for windows on ubuntu?

### ISSUE THREAD

**Issue by dan-myles** [tauri-apps/tauri-action#783]
Just wanna use this action to build for windows on ubuntu! <3

**Comment by FabianLars** [comment]
Well, https://tauri.app/v1/guides/building/cross-platform#experimental-build-windows-apps-on-linux-and-macos should work in github's CI too but it has native windows (and macos) runners you can use to directly build _on_ windows/macos _for_ windows/macos (the examples assume that this is what you want so if it is, you can pretty much just copy paste it).
