### ISSUE TITLE
[bug] The build results on the Mac platform are confusing. The aarch64.dmg file cannot be launched on Macs with Intel, M1, and M2 chips, while the x64.dmg file can be successfully launched on Intel, M1, and M2.

### ISSUE THREAD

**Issue by heneyin** [tauri-apps/tauri-action#791]
The build results on the Mac platform are confusing. The aarch64.dmg file cannot be launched on Macs with Intel, M1, and M2 chips, while the x64.dmg file can be successfully launched on Intel, M1, and M2.

![image](https://github.com/tauri-apps/tauri-action/assets/17850697/f1e35339-c3ce-41ab-b99d-6f6aaa4ae8bf)

According to the official documentation, aarch64 is intended for Apple chips, while x64 is meant for Intel chips. However, the actual results are contrary to this description, which is quite confusing. I am unsure whether this discrepancy is due to a bug in tauri-action or if I am using it incorrectly.

My test demo：https://github.com/heneyin/tauri-demo/releases/tag/v0.0.0 

Thanks

**Comment by ImLunaHey** [comment]
im having the same issue. the arch build shows as corrupted whereas the x86 version loads fine. im on a M2 macbook.

https://github.com/ImLunaHey/cozy-game/releases

**Comment by FabianLars** [comment]
macos is simply stricter about arm apps and now requires it to be signed. Until Apple fixes this, you can make it behave like x86 apps by signing it with an empty certificate, to do this, add `"signingIdentity": "-"` to your tauri.conf.json file (inside `tauri.bundle.macOS`.

**Comment by ImLunaHey** [comment]
why is this closed? currently the docs suggest you can use this and it doesn't work..

shouldnt the docs be updated?

**Comment by FabianLars** [comment]
I closed it because it's not a tauri-action specific problem, if you build on a local macos system and then try it on another it will have the same issue.

It's kinda tracked here https://github.com/tauri-apps/tauri/issues/8763 and also on the radar for the v2 docs.
