### ISSUE TITLE
No releases after action is done , 

### ISSUE THREAD

**Issue by MrChaker** [tauri-apps/tauri-action#795]
Done in 249.52s.
Looking for artifacts in:
D:\a\upcount-tauri\upcount-tauri\src-tauri\target\release\bundle\msi\Upcount_0.1.0_x64_en-US.msi
D:\a\upcount-tauri\upcount-tauri\src-tauri\target\release\bundle\msi\Upcount_0.1.0_x64_en-US.msi.zip
D:\a\upcount-tauri\upcount-tauri\src-tauri\target\release\bundle\msi\Upcount_0.1.0_x64_en-US.msi.zip.sig
D:\a\upcount-tauri\upcount-tauri\src-tauri\target\release\bundle\nsis\Upcount_0.1.0_x64-setup.exe
D:\a\upcount-tauri\upcount-tauri\src-tauri\target\release\bundle\nsis\Upcount_0.1.0_x64-setup.nsis.zip
D:\a\upcount-tauri\upcount-tauri\src-tauri\target\release\bundle\nsis\Upcount_0.1.0_x64-setup.nsis.zip.sig
Found artifacts:
D:\a\upcount-tauri\upcount-tauri\src-tauri\target\release\bundle\msi\Upcount_0.1.0_x64_en-US.msi
D:\a\upcount-tauri\upcount-tauri\src-tauri\target\release\bundle\nsis\Upcount_0.1.0_x64-setup.exe
Looking for a draft release with tag app-v0.1.0...
Found draft release with tag app-v0.1.0 on the release list.
Deleting existing Upcount_0.1.0_x64_en-US.msi...
Uploading Upcount_0.1.0_x64_en-US.msi...
Deleting existing Upcount_0.1.0_x64-setup.exe...
Uploading Upcount_0.1.0_x64-setup.exe...
Asset and signature not found for the updater JSON. Skipping upload...

Why do I need the updater JSON , I just want to publish the releases

**Comment by FabianLars** [comment]
Are you sure there is no release? The logs say that the action uploaded the assets it found. If you copied the default template it will be a draft release. Draft releases do not show up on the repo main page so you have to navigate to the /releases subpage to view them.

**Comment by MrChaker** [comment]
ah ok , I thgouht releaseDraft: true was meant to do the opposite
