### ISSUE TITLE
Action fails to find appimage built on self-hosted aarch64 device

### ISSUE THREAD

**Issue by jp-bennett** [tauri-apps/tauri-action#798]
We're using this action with a self-hosted arm64 runner, to build a Linux .deb/appimage. The problem is that the appimage gets names *.aarch64.AppImage, but the action looks for an artifact names *.arm64.AppImage. 

https://github.com/meshtastic/network-management-client/actions/runs/9199973425/job/25305699131

**Comment by FabianLars** [comment]
Thanks for the report. Can you test the `fix/arm-appimage` branch? (Replace tauri-action@v0 with tauri-action@fix/arm-appimage in your workflow)

p.s. i think this is actually a tauri bug.

**Comment by jp-bennett** [comment]
Yea, that did the trick, thanks!

**Comment by FabianLars** [comment]
Cool, thanks for testing. I'll merge it once I'm home so remember to change back your workflow as the branch will be deleted then :)
