### ISSUE TITLE
MacOS builds are quarantined

### ISSUE THREAD

**Issue by GRA0007** [tauri-apps/tauri-action#824]
I'm using tauri `2.0.0-beta.22`, and this action to build my app, and I've noticed that none of the MacOS builds are working. When I run `yarn tauri build` locally, the build works fine, but the artifacts produced by the action show a dialog with `“MyApp.app” is damaged and can’t be opened. You should move it to the Bin.` when trying to open them.

Edit: Apparently running `xattr -c <path/to/application.app>` fixes it, but I can't expect users to run this, and I can't afford to pay Apple to sign my app, so how can I stop Apple from quarantining my app?

**Comment by FabianLars** [comment]
> so how can I stop Apple from quarantining my app?

In your tauri.conf.json you can set `bundle.macOS.signingIdentity` to `"-"` to enable ad-hoc signing. This will make right click -> open work for now (i assume apple will break this at some point too).
