### ISSUE TITLE
Validation Failed: {"resource":"ReleaseAsset","code":"already_exists","field":"name"} - https://docs.github.com/rest

### ISSUE THREAD

**Issue by kjxbyz** [tauri-apps/tauri-action#848]
https://github.com/cyf/faforever/actions/runs/9773323689/job/26980145455#step:12:1088

**Comment by FabianLars** [comment]
Can you trigger a rerun of the failed build? This looks like unlucky timing.

**Comment by kjxbyz** [comment]
I triggered it once.

**Comment by FabianLars** [comment]
Hmm, i ran it twice now and it didn't fail https://github.com/tauri-apps/tauri-action/actions/runs/9775283981/job/26986420908

Can you try `uses: tauri-apps/tauri-action@v0.5.6` maybe? 0.5.7 had a few issues and maybe we did not fix everything in 0.5.8 yet 🤔

**Comment by FabianLars** [comment]
Ah, it may be a conflict between debug and release builds. I'll run our CI with both enabled again.

**Comment by kjxbyz** [comment]
After removing `includeDebug`, it works fine.
