### ISSUE TITLE
Signature verification fails when updating application build with v0.5.6 to one built with v0.5.9 

### ISSUE THREAD

**Issue by dwilkolek** [tauri-apps/tauri-action#852]
I have application built with action v0.5.6. Today I released new version of my app that used v0.5.9. Old version of my application cannot verify signature of new one. When I build application with v0.5.6 it seems to work.

Related repository: https://github.com/dwilkolek/wombat

**Comment by FabianLars** [comment]
The action does not generate nor touch the signatures, that's all tauri and tauri's cli. The only thing that could go wrong is that it writes the wrong .sig files into latest.json but that didn't seem to be the case either (only checked .msi before you removed the release).

I'll wait for your current CI run to complete before looking into it again, just wanted to clear that part up already.

**Comment by dwilkolek** [comment]
I've published prerelease that used `v0`. I've experienced error on mac os. I'll double check on windows

**Comment by dwilkolek** [comment]
Windows machine updated without any issues. 
Looks like macos is affected.

**Comment by dwilkolek** [comment]
Looks like something went wrong with @tauri-apps/cli  update for macos from 1.5.13 to 1.5.14. [Rollback  to 1.5.13](https://github.com/dwilkolek/wombat/pull/106) fixed the issue.  [Updating to 1.6.0](https://github.com/dwilkolek/wombat/pull/107) also fixed the issue.

Thanks for the insights. Not sure If I should report this issue at https://github.com/tauri-apps/tauri . Looks like any other version is fixing this. If I read releases correctly the only change that happen in 1.5.14 was this [PR](https://github.com/tauri-apps/tauri/pull/9659) and it doesn't seem related.

**Comment by FabianLars** [comment]
tbh no need to report an issue over there. This seems more like a fluke of some kind and we generally don't backport bugfixes from one 1.x release to another, so if 1.6.0 works that's good enough - also, no idea what we'd have to backport, as you said, there were no related changes (and also, it was just your app so there must be some condition we're not seeing here)
