### ISSUE TITLE
Able to build v2 on Linux, not Windows or MacOS

### ISSUE THREAD

**Issue by jasonterando** [tauri-apps/tauri-action#882]
I don't _think_ is is a dupe of [724](https://github.com/tauri-apps/tauri-action/issues/742), but I have a similar challenge.  My Debian build works, but now Windows OS or Linux.  Attached is the Windows task log with verbose enabled.

Thanks!

[logs_26971053934.zip](https://github.com/user-attachments/files/16553378/logs_26971053934.zip)

**Comment by FabianLars** [comment]
The logs look like you simply disabled the windows and macos specific bundle targets in the bundle.targets config in tauri.conf.json (`app` and `dmg` for macos - `msi` and/or `nsis` for windows).

Just the binary isn't enough on macOS (that's how the os works really), and on Windows, while the exe itself mostly works, tauri still expects to be installed via installers (if you don't care about that, which can be fine, you'd hit https://github.com/tauri-apps/tauri-action/issues/302)

**Comment by jasonterando** [comment]
DOH!  Thanks, I enabled RPM as well and got that build.  Good times!
