### ISSUE TITLE
`tauri.conf.json` error on build

### ISSUE THREAD

**Issue by setoelkahfi** [tauri-apps/tauri-action#886]
Hello, I'm trying to use this action (latest) for a Tauri v1 project `("@tauri-apps/cli": "^1.5.14",`). I got these errors when building for release:

```bash
Run tauri-apps/tauri-action@v0
  with:
    tagName: app-v__VERSION__
    releaseName: App v__VERSION__
    releaseBody: See the assets to download this version and install.
    releaseDraft: true
    prerelease: false
    args: --target x86_64-apple-darwin
    projectPath: .
    includeDebug: false
    includeRelease: true
    includeUpdaterJson: true
    updaterJsonKeepUniversal: false
  env:
    CARGO_HOME: /Users/runner/.cargo
    CARGO_INCREMENTAL: 0
    CARGO_TERM_COLOR: always
    GITHUB_TOKEN: ***
running npm [ 'install', '-g', '@tauri-apps/cli' ]

added [2](https://github.com/pathtorepo/actions/runs/10338023139/job/28615561509#step:7:2) packages in 1s

1 package is looking for funding
  run `npm fund` for details
running tauri [ 'build', '--target', 'x86_6[4](https://github.com/pathtorepo/actions/runs/10338023139/job/28615561509#step:7:4)-apple-darwin' ]
       Error `tauri.conf.json` error on `build`: Additional properties are not allowed ('devUrl', 'frontendDist' were unexpected)
       Error `tauri.conf.json` error: Additional properties are not allowed ('app', 'bundle', 'identifier', 'productName', 'version' were unexpected)
Error: Command failed with exit code 1: tauri build --target x8[6](https://github.com/pathtorepo/actions/runs/10338023139/job/28615561509#step:7:6)_64-apple-darwin
```

Strangely, I don't have those properties in my tauri.conf.json file. It's a mono repo setup, so I have the `working-directory` option in the workflow file. And it builds successfully locally. 

Any pointers?

**Comment by FabianLars** [comment]
If the action can't find a tauri cli installation it will install the latest stable version. Make sure you have a cli installed and maybe set `tauriScript` to that (should only be needed if it's not installed via package.json). Also, `working-directory` only applies to steps with `run`, not to steps that use actions, try the action's `projectPath` config instead.

**Comment by setoelkahfi** [comment]
My bad, that was the problem. I had another setup node action that didn't work without the `working-directory` option, so I had this at the workflow level:

```yaml
defaults:
  run:
    working-directory: frontend/desktop
```
I thought that should be reflected in the workflow for all jobs.
