### ISSUE TITLE
Build fails due to invalid tauri config.

### ISSUE THREAD

**Issue by binarybaron** [tauri-apps/tauri-action#904]
I'm building a Tauri v2 App and trying to build binaries using the CI.

The Github action fails to build the binaries. The error is the following:

```running tauri [ 'build' ]
       Error `tauri.conf.json` error on `build`: Additional properties are not allowed ('devUrl', 'frontendDist' were unexpected)
       Error `tauri.conf.json` error: Additional properties are not allowed ('app', 'bundle', 'identifier', 'productName', 'version' were unexpected)
```

See here for the full logs: https://github.com/UnstoppableSwap/xmr-btc-swap/actions/runs/10745497178/job/29804634410

My config looks like this:

```
{
  "productName": "unstoppableswap-gui-rs",
  "version": "0.1.0",
  "identifier": "net.unstoppableswap.gui",
  "build": {
    "devUrl": "http://localhost:1420",
    "frontendDist": "../src-gui/dist",
    "beforeDevCommand": {
      "cwd": "../src-gui",
      "script": "yarn run dev"
    },
    "beforeBuildCommand": {
      "cwd": "../src-gui",
      "script": "yarn run build"
    }
  },
  "app": {
    "windows": [
      {
        "title": "unstoppableswap-gui-rs",
        "width": 800,
        "height": 600
      }
    ],
    "security": {
      "dangerousDisableAssetCspModification": true
    }
  },
  "bundle": {
    "active": true,
    "targets": "all",
    "icon": [
      "icons/32x32.png",
      "icons/128x128.png",
      "icons/128x128@2x.png",
      "icons/icon.icns",
      "icons/icon.ico"
    ]
  }
}
```

This seems to me like it's expecting a v1 config perhaps?

You can view the full source code of my project here: https://github.com/UnstoppableSwap/xmr-btc-swap

**Comment by gwbiubiu** [comment]
I have encountered the same issue.

**Comment by FabianLars** [comment]
If the action can't find a tauri cli in the root and if `tauriScript` is not defined the action will download the latest stable cli which at this moment is still v1. In your workflow changing projectPath to `projectPath: src-gui` should probably work (that's where the cli package is).

**Comment by binarybaron** [comment]
My tauri project (including the Cargo.toml file) is located in src-tauri.

Should I add the tauri-cli to the dev dependencies?

**Comment by FabianLars** [comment]
> My tauri project (including the Cargo.toml file) is located in src-tauri.

I looked at your project before i sent my suggestion so i'm aware. That said, i'm not sure if it works, projectPath may require the src-tauri directory to be a child of the frontend directory and fail if they are next to each (like in your project).

> Should I add the tauri-cli to the dev dependencies?

No, dev-dependencies in Cargo.toml work differently than in package.json and doesn't support binaries.

----

Your `npx` `tauriScript` config is a good alternative though. Since it's still failing, try removing the projectPath config, and if that still fails it _should_ be a frontend set up failure not directly related to tauri or this action but idk

**Comment by ChenghaoQ** [comment]
Check the tauri-cli version, see if the tauri-cli is still in v1
```
cargo tauri --version
```

**Comment by frehberg** [comment]
it seems, once tauri-cli v1 has been installed with cargo, it does not upgrade to v2.

Therefore, deinstall tauri-cli and re-install latest version v2

```
cargo tauri --version
cargo uninstall tauri-cli
cargo install tauri-cli
cargo tauri --version
```
