### ISSUE TITLE
[Feature Request] Add Ubuntu-24.04 build support

### ISSUE THREAD

**Issue by srsng** [tauri-apps/tauri-action#910]
Need tauri github action supports platform Ubuntu-24.04.

**Comment by FabianLars** [comment]
It already does but it's in beta: https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

Also, only tauri v2 supports 24.04 see https://github.com/tauri-apps/tauri/issues/9662
