### ISSUE TITLE
Build fails for macOS --target x86_64-apple-darwin due to OpenSSL error

### ISSUE THREAD

**Issue by heyxmirko** [tauri-apps/tauri-action#915]
Hi, I'm encountering an issue when trying to build a release for macOS using --target x86_64-apple-darwin with Tauri in my GitHub Actions workflow. The build for aarch64-apple-darwin, as well as the builds for Windows and Ubuntu, work just fine, but the x86_64 macOS target fails due to an OpenSSL-related issue.

Here is the relevant portion of the error:
```
error: failed to run custom build command for `openssl-sys v0.9.103`

Caused by:
  process didn't exit successfully: `/Users/runner/work/autotest/autotest/src-tauri/target/release/build/openssl-sys-7e544572527d7112/build-script-main` (exit status: 101)
...
Could not find directory of OpenSSL installation, and this `-sys` crate cannot proceed without this knowledge. If OpenSSL is installed and this crate had trouble finding it, you can set the `OPENSSL_DIR` environment variable for the compilation process.

$HOST = aarch64-apple-darwin
$TARGET = x86_64-apple-darwin
openssl-sys = 0.9.103
```

I would appreciate any guidance on how to resolve this issue. Thanks in advance!

**Comment by FabianLars** [comment]
I typically recommend trying to get rid of openssl. Most rust crates have feature flag to switch from openssl to rustls.
If this is not possible then the next easiest option is to add this to your Cargo.toml 
```toml
openssl-sys = { version = "0.9", features = ["vendored"] }
```

If that doesn't work either i hope someone else can chime in cause i don't know how to set up openssl for cross compilation on macos.

**Comment by heyxmirko** [comment]
Adding the dependency to the Cargo.toml worked! Thanks!
