### ISSUE TITLE
macOS arm build succeded but cannot be installed: `Splitfire` is damaged and cannot be opended

### ISSUE THREAD

**Issue by smbcloudXYZ** [tauri-apps/tauri-action#919]
I never really tried the build from the CI because I'm using the macOS M1 for development. When I do, I got errors like so:

<img width="924" alt="Screenshot 2024-09-23 at 08 14 03" src="https://github.com/user-attachments/assets/4590ee69-1f47-4aa9-8435-37e7aca3eb0d">

<img width="269" alt="Screenshot 2024-09-23 at 08 13 13" src="https://github.com/user-attachments/assets/d3f3275c-409d-4e24-a6b7-8f4689015069">

The build is succeed. 

Doesn't happen if I build it with my laptop. Any clue?

**Comment by FabianLars** [comment]
https://github.com/tauri-apps/tauri-action/issues/866
