### ISSUE TITLE
mac aarch64 bundle not uploaded, logs don't show anything extrange

### ISSUE THREAD

**Issue by cardo-podcast** [tauri-apps/tauri-action#935]
Hi, If I'm not wrong the @dev version of this script don't upload assets without throwing any error.

Here is the [github action](https://github.com/cardo-podcast/cardo/blob/master/.github/workflows/publish.yml)

Here are the [logs](https://github.com/cardo-podcast/cardo/actions/runs/11307099539/job/31470508566)

Other releases where uploaded sucessfully.

Anything you want to know be free to ask, thanks!

**Comment by FabianLars** [comment]
Hmm that's a weird one. According to the logs everything went well. Can you check in https://github.com/cardo-podcast/cardo/releases whether there's a (duplicate) release marked as draft? (Only repo owners can see drafts so i can't check)

**Comment by cardo-podcast** [comment]
> Hmm that's a weird one. According to the logs everything went well. Can you check in https://github.com/cardo-podcast/cardo/releases whether there's a (duplicate) release marked as draft? (Only repo owners can see drafts so i can't check)

That's exactly what happened, it's the first time that happened to me, maybe is a strange case, be free to close/stale the issue.
Thank you!

**Comment by FabianLars** [comment]
okay i'll close this for now and will re-open if this happens more often.
