### ISSUE TITLE
latest.json is not uploaded with error: Signature not found

### ISSUE THREAD

**Issue by florianzachstailoryoung** [tauri-apps/tauri-action#943]
In an older version of my project, generation of latest.json worked. I then switched to Tauri v2. Now i got everything to work again, but now latest.json is not generated. In the Github Action Pipeline, I get the error `Signature not found for the updater JSON. Skipping upload...`

In the action I defined the env variables 
 - `GITHUB_TOKEN`, 
 - `TAURI_SIGNING_PRIVATE_KEY`, 
 - `TAURI_SIGNING_PRIVATE_KEY_PASSWORD`
 , as well as the with-variables:
 - `tagName`
 - `releaseName`
 - `releaseBody`
 - `releaseDraft`
 - `prerelease` = false
 - `includeUpdaterJson` = true
 - `owner`
 - `repo`
 - `releaseCommitish`
 - `args`
 
 With the same variables (but renamed Tauri env vars), it worked in Tauri v1.
 What could be the source of the Signature Error message?

**Comment by FabianLars** [comment]
Did you also set generateUpdaterArtifacts in tauri.conf.json? https://v2.tauri.app/plugin/updater/#building

**Comment by florianzachstailoryoung** [comment]
Hey, thank you for your quick response! Funnily, just after writing I looked into the documentation again, and I tried using `createUpdaterArtifacts`, which seems to not have been necessary in Tauri v1. Just after confirming that it actually worked, I received your Message. At least now the error message leads to something on Google. Sorry for the clutter, Thank you for your response!
