### ISSUE TITLE
Tauri 2.0 "command not found" despite setting project path

### ISSUE THREAD

**Issue by BjornTheProgrammer** [tauri-apps/tauri-action#944]
Thank you for this action!

I'm just having an issue, where every build target fails, despite setting the project path. It just fails stating `sh: tauri: command not found`.

The repo has two sections, `tauri-app`, and `pico-firmware`. `tauri-app` was just generated from create-tauri-app, so I can't imagine why this wouldn't be working.

The failed job can be found [here](https://github.com/Devils-Prosthetics/DevilMechanicalTester/actions/runs/11521545433/job/32075436547).

Any and all help would be greatly appreciated!

**Comment by FabianLars** [comment]
i _think_ the issue is the `yarn install` step because that also tries to run in the top-level dir where no package.json is. if you change it to `cd tauri-app && yarn install` it _should_ work.

**Comment by BjornTheProgrammer** [comment]
That worked! Thank you so much
