### ISSUE TITLE
add a new one to the release search folders

### ISSUE THREAD

**Issue by BlackRam-oss** [tauri-apps/tauri-action#963]
Hi I modified the default script to also add the android apk release.
The script works the only thing is that at the end it gives me an error telling me that it has not found any new files to add in the release /src-tauri/target/release/ in the default release folder.

the reason is that the apk is saved in src-tauri/gen/android/

so I was wondering if it is possible to add a new one to the release search folders in addition to the default one.
I read the documentation, but I didn't find a way.

**Comment by FabianLars** [comment]
mobile support is tracked here: https://github.com/tauri-apps/tauri-action/issues/525 / https://github.com/tauri-apps/tauri-action/pull/924
general custom path support is not planned but there are enough other github actions to upload something to a release (tauri-action will output the releaseId so you can re-use that)
