### ISSUE TITLE
Run echo ::set-env name=PACKAGE_VERSION::$(node -p "require('./package.json').version")

### ISSUE THREAD

**Issue by aafnnp** [tauri-apps/tauri-action#97]
Run echo ::set-env name=PACKAGE_VERSION::$(node -p "require('./package.json').version")
Error: Unable to process command '::set-env name=PACKAGE_VERSION::0.1.0' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by lucasfernog** [comment]
README hasn't been updated in a while, i'm updating it right now. For reference, it should be `run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV` since set-env was deprecated.
