### ISSUE TITLE
[BUG] latest.json is not being added

### ISSUE THREAD

**Issue by eythaann** [tauri-apps/tauri-action#974]
Since these days, latest.json is not being added to the release of my project, but two days ago it was working fine, some changes done on [release v.0.5.17](https://github.com/tauri-apps/tauri-action/releases/tag/action-v0.5.17) on tauri-action project could break this.

with `latest.json` file: https://github.com/eythaann/Seelen-UI/releases/tag/v2.0.9
no `latest.json` present: https://github.com/eythaann/Seelen-UI/releases/tag/v2.0.10

**Comment by FabianLars** [comment]
Closing in favor of #975
