### ISSUE TITLE
The Rust cache is not functioning on the mac x86_64 target.

### ISSUE THREAD

**Issue by LimLLL** [tauri-apps/tauri-action#980]
The cache works fine on Mac's AArch64, Ubuntu and Windows, but not on Mac's x86_64 architecture. Is this an expected behavior?
<img width="674" alt="CleanShot 2024-12-13 at 13 11 11@2x" src="https://github.com/user-attachments/assets/4bf0ac82-28bf-4f07-8ddb-69df559a1628" />

**Comment by FabianLars** [comment]
Can you share the workflow file and the logs of the cache step?

**Comment by LimLLL** [comment]
This issue is quite random mayby? (im new to github action) [My workflow file](https://raw.githubusercontent.com/LimLLL/test_tauri_updater/refs/heads/main/.github/workflows/tauri_publish.yml)

1. **First Workflow Run:** (https://github.com/LimLLL/test_tauri_updater/actions/runs/12315435671)
   - Here has a minor issue as well. When I use Chinese characters in the `productName` variable within `tauri.conf.json`, the action fails to generate `latest.json` for non-Windows platforms.  I set `productName` to "test" in `tauri.windows.conf.json` and "测试" in `tauri.conf.json`. The Windows build correctly generates `latest.json`, but the other three platforms (macOS x86_64, macOS aarch64, and Ubuntu) do not.

2. **Second Workflow Run:** (https://github.com/LimLLL/test_tauri_updater/actions/runs/12315709912/job/34374470895)
   - The issue now occurs with the `aarch64-apple-darwin` target, but not the `x86_64-apple-darwin` target. The Ubuntu and Windows builds work correctly and utilize the cache.

**Comment by LimLLL** [comment]
> Can you share the workflow file and the logs of the cache step?

This issue is quite random maybe? (im new to github action) [My workflow file](https://raw.githubusercontent.com/LimLLL/test_tauri_updater/refs/heads/main/.github/workflows/tauri_publish.yml)

1. **First Workflow Run:** (https://github.com/LimLLL/test_tauri_updater/actions/runs/12315435671)
   - Here has a minor issue as well. When I use Chinese characters in the `productName` variable within `tauri.conf.json`, the action fails to generate `latest.json` for non-Windows platforms.  I set `productName` to "test" in `tauri.windows.conf.json` and "测试" in `tauri.conf.json`. The Windows build correctly generates `latest.json`, but the other three platforms (macOS x86_64, macOS aarch64, and Ubuntu) do not (see the output for each target in this workflow run).

2. **Second Workflow Run after the First run fully complete :** (https://github.com/LimLLL/test_tauri_updater/actions/runs/12315709912/job/34374470895)
   - The issue now occurs with the `aarch64-apple-darwin` target, but not the `x86_64-apple-darwin` target. The Ubuntu and Windows builds work correctly and utilized the cache.
   - I've change all `productName` to `test` at this time of run which all platforms generate `latest.json` correctly


Please let me know if more info required.

**Comment by FabianLars** [comment]
Ah that workflow is from our docs or the tauri-action repo, right? Then it's my fault. By default the rust-cache action only looks at the runner's own platform which is the same for both builds. This should help:
```yml
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          key: ${{ matrix.args }}
```

**Comment by LimLLL** [comment]
> Ah that workflow is from our docs or the tauri-action repo, right? Then it's my fault. By default the rust-cache action only looks at the runner's own platform which is the same for both builds. This should help:
> 
> ```yaml
>       - name: Rust cache
>         uses: swatinem/rust-cache@v2
>         with:
>           workspaces: './src-tauri -> target'
>           key: ${{ matrix.args }}
> ```

thanks for your reply. Yes, the workflow is from Tauri docs. I'm currently testing it, and I will let you know the result asap. And could you please take a look at the Chinese characters issue, thanks in advance.

**Comment by LimLLL** [comment]
> Ah that workflow is from our docs or the tauri-action repo, right? Then it's my fault. By default the rust-cache action only looks at the runner's own platform which is the same for both builds. This should help:
> 
> ```yaml
>       - name: Rust cache
>         uses: swatinem/rust-cache@v2
>         with:
>           workspaces: './src-tauri -> target'
>           key: ${{ matrix.args }}
> ```

cache issue solved by adding `key: ${{ matrix.args }}`, thanks

**Comment by LimLLL** [comment]
The Chinese characters issue turns out to be a limitation of GitHub, which does not allow uploading a file with Chinese characters in the filename. Is it possible to add a variable like `renameBundledName` after the Tauri build is completed and before uploading it to the GitHub release to modify the output filename like from `测试-0.2.0-1.x86_64.rpm` to `app-0.2.0-1.x86_64.rpm` to avoid failure of latest.json generation?

**Comment by LimLLL** [comment]
For someone who has the similiar issue on use Chinese characters for productName and failed to upload to github release and latest.json generation, here is a quite fix (btw, this might not be the optimal option.):
1. fork the repository
2. make some changes:
    - changes to src/build.ts:
        - `import { existsSync, renameSync } from 'node:fs';` 
        - add a new parameter `renameArtifacts: string` to `buildProject` function
        -  <img width="725" alt="CleanShot 2024-12-16 at 13 09 44@2x" src="https://github.com/user-attachments/assets/61e3c7bd-ce96-4104-b1db-92d02c320d1a" />
    - changes to action.yml
        - add `renameArtifacts:
    description: 'Whether to rename the artifacts or not, if yes, enter a string that will be used as a prefix for the artifacts'` under inputs category
    - changes to src/index.ts 
        - `const renameArtifacts = core.getInput('renameArtifacts');`
        - ![CleanShot 2024-12-16 at 13 15 56@2x](https://github.com/user-attachments/assets/a193b728-7348-441e-b42a-85ffe957e1f9)
3. pnpm build
4. make a release and publish to action marketplace for temporary usage

**Comment by LimLLL** [comment]
For someone who has the similiar issue on use Chinese characters for productName and failed to upload to github release and latest.json generation, here is a quite fix (btw, this might not be the optimal option.):
1. fork the repository
2. make some changes:
    - changes to src/build.ts:
        - `import { existsSync, renameSync } from 'node:fs';` 
        - add a new parameter `renameArtifacts: string` to `buildProject` function
        -  <img width="795" alt="CleanShot 2024-12-16 at 13 36 00@2x" src="https://github.com/user-attachments/assets/a583d325-386a-4fc3-a823-6b7a16908485" />

    - changes to action.yml
        - add `renameArtifacts:
    description: 'Whether to rename the artifacts or not, if yes, enter a string that will be used as a prefix for the artifacts'` under inputs category
    - changes to src/index.ts 
        - `const renameArtifacts = core.getInput('renameArtifacts');`
        - ![CleanShot 2024-12-16 at 13 15 56@2x](https://github.com/user-attachments/assets/a193b728-7348-441e-b42a-85ffe957e1f9)
3. pnpm build
4. make a release and publish to action marketplace for temporary usage
