### ISSUE TITLE
Version v0.5.17 fails to create the artifact `latest.json` due to missing signature files, even if those were create according to the action log

### ISSUE THREAD

**Issue by hrzlgnm** [tauri-apps/tauri-action#983]
After updating to v0.5.17 I had an issue creating release artifacts with auto updates due to the artifact `latest.json` not being created, so I went back to v0.5.16 in the mean time .

This happened while building and publishing the following release:

https://github.com/hrzlgnm/mdns-browser/releases/tag/mdns-browser-v0.10.5

The log excerpt of the publish action:
```
   Finished 1 bundle at:
        D:\a\mdns-browser\mdns-browser\target\release\bundle\nsis\mdns-browser_0.10.5_x64-setup.exe

    Finished 1 updater signature at:
        D:\a\mdns-browser\mdns-browser\target\release\bundle\nsis\mdns-browser_0.10.5_x64-setup.exe.sig

Looking for artifacts in:
D:\a\mdns-browser\mdns-browser\target\release\bundle\msi\mdns-browser_0.10.5_x64_en-US.msi
D:\a\mdns-browser\mdns-browser\target\release\bundle\msi\mdns-browser_0.10.5_x64_en-US.msi.sig
D:\a\mdns-browser\mdns-browser\target\release\bundle\msi\mdns-browser_0.10.5_x64_en-US.msi.zip
D:\a\mdns-browser\mdns-browser\target\release\bundle\msi\mdns-browser_0.10.5_x64_en-US.msi.zip.sig
D:\a\mdns-browser\mdns-browser\target\release\bundle\nsis\mdns-browser_0.10.5_x64-setup.exe
D:\a\mdns-browser\mdns-browser\target\release\bundle\nsis\mdns-browser_0.10.5_x64-setup.exe.sig
D:\a\mdns-browser\mdns-browser\target\release\bundle\nsis\mdns-browser_0.10.5_x64-setup.nsis.zip
D:\a\mdns-browser\mdns-browser\target\release\bundle\nsis\mdns-browser_0.10.5_x64-setup.nsis.zip.sig
Found artifacts:
D:\a\mdns-browser\mdns-browser\target\release\bundle\nsis\mdns-browser_0.10.5_x64-setup.exe
D:\a\mdns-browser\mdns-browser\target\release\bundle\nsis\mdns-browser_0.10.5_x64-setup.exe.sig
Found release with tag mdns-browser-v0.10.5.
Deleting existing mdns-browser_0.10.5_x64-setup.exe...
Uploading mdns-browser_0.10.5_x64-setup.exe...
Signature not found for the updater JSON. Skipping upload...
```

The workflow used for building at that point in time is available here:

https://github.com/hrzlgnm/mdns-browser/blob/mdns-browser-v0.10.5/.github/workflows/desktop-tauri.yml

Which is a reusable workflow definition, used by the following publish workflow:
https://github.com/hrzlgnm/mdns-browser/blob/mdns-browser-v0.10.5/.github/workflows/desktop-publish.yml

After downgrading and creating another pre-release from a Draft created by a release drafter the artifact `latest.json` was created again:
https://github.com/hrzlgnm/mdns-browser/releases/tag/mdns-browser-v0.10.6

**Comment by FabianLars** [comment]
This is a known issue and the reason why the v0 and v0.5 tags point to v0.5.16 instead. This issue was also fixed for a while already on the dev branch.

I'll release 0.5.18 tomorrow.
